### ISSUE TITLE
Problem with posts#show

### ISSUE THREAD

**Issue by okwon** [producthunt/producthunt-api#100]
Hi. I wanted to collect all products that are not featured. It seemed to me that posts/all endpoint only gave me a list of featured products, so I decided to use posts/1 endpoint instead. However, this endpoint gave me the same product information, even though I changed ID. For instance:

https://api.producthunt.com/v1/posts/1?id=30000

This gives me product with id 27317.

**Comment by andreasklinger** [comment]
i am cleaning up the issues - this hasn't been responded to yet - sorry for that
if this is still an active issue please let me know and i will take a look!
