### ISSUE TITLE
Write Permission Error when trying to follow/unfollow user

### ISSUE THREAD

**Issue by Braunbaer** [producthunt/producthunt-api#101]
I'm trying to follow/unfollow a user but no matter what I try i always get the following error:

```
{
"error": "access_denied",
"error_description": "Sorry. You are not allowed to do this. If you suspect this is an error please contact our support team.",
"details": "ErrorHandling::WritePermissions: Your application is not allowed to write data on behalf of the user"
}
```
The authentication is user based and the access token seems to be valid since I get a different error when I set a wrong one on purpose.

Does anybody know how fix this or how to get write permission for an app?

**Comment by RStankov** [comment]
Unfortunately at this point the API is read-only, and we don't give out write permissions.
