### ISSUE TITLE
I can't find docs for authorize

### ISSUE THREAD

**Issue by asimona** [producthunt/producthunt-api#102]
I can't find the authorize page.
When I try to enter https://api.producthunt.com/v1/docs/oauth_user_authentication/oauth_authorize_ask_for_access_grant_code_on_behalf_of_the_user it's redirecting to https://api.producthunt.com/v1/docs.

**Comment by RStankov** [comment]
Weird, this page always "disappears" for some reason. I'll look into it.

**Comment by rohillion** [comment]
What's up @RStankov? Any joy with this part of the documentation? Is there any chance you could  provide the parameters I should pass to the entry point? Cheers!

**Comment by RStankov** [comment]
@asimona I restored the doc page - https://api.producthunt.com/v1/docs/oauth_client_only_authentication/oauth_token_ask_for_client_level_token

@rohillion you need to provide 3 params:

| param | description |
| ------ | ------------ |
| client_id  | The id of your application |
| client_secret | The secret of your application |
| grant_type required | `client_credentials` |
