### ISSUE TITLE
posts#all newest under 10 upvotes

### ISSUE THREAD

**Issue by rohillion** [producthunt/producthunt-api#103]
What's up guys,
Any chance we can get not just the most popular product but the newest too? I realised I am getting just the ones with more than 10 upvotes.

Cheers!

**Comment by rohillion** [comment]
Sorry guys me again. I thought I was wrong but I am not able to get the newest posts under 10 upvotes. Is it possible to get them somehow and I am missing something?

**Comment by andreasklinger** [comment]
i am cleaning up the issues - this hasn't been responded to yet - sorry for that
if this is still an active issue please let me know and i will take a look!
