### ISSUE TITLE
API request with developer token returning unauthorized_oauth

### ISSUE THREAD

**Issue by sarimhaq** [producthunt/producthunt-api#104]
I am making a simple GET/v1/posts request with my developer access token using **fiddler** but I keep getting the unauthorized_ oauth error. Here are the details:

Request URL: 
https://api.producthunt.com/v1/posts

Header: 
Accept: application/json
Content-Type: application/json
Authorization: Bearer **my_token**
Host: api.producthunt.com

Please help. Thanks.

**Comment by andreasklinger** [comment]
i am cleaning up the issues - this hasn't been responded to yet - sorry for that
if this is still an active issue please let me know and i will take a look!

**Comment by ishu3101** [comment]
I'm also getting the same issue. See my post on [stackoverflow](http://stackoverflow.com/questions/40012215/producthunt-api-authentication-using-jquery)

**Comment by hansmosh** [comment]
@andreasklinger I am seeing the same thing. Using Postman to make my requests to api.producthunt.com/v1/posts and for some reason it changes my headers to this when I make the request:
`Authorization:Basic Og==
Accept:application/json
Content-Type:application/json
Host:api.producthunt.com`

I've never seen that happen before with Postman.

`{
  "error": "unauthorized_oauth",
  "error_description": "Please supply a valid access token. Refer to our api documentation about how to authorize an api request. Please also make sure you require the correct scopes. Eg \"private public\" for to access private endpoints."
}`

When I use `curl` I just don't get any response:
`curl -H "Authorization: Bearer my_token" -H "Accept:application/json" -H "Content-Type:application/json" -H "Host:api.producthunt.com" http://api.producthunt.com/v1/posts`
