### ISSUE TITLE
Allow 'public' apps to access the /me endpoint

### ISSUE THREAD

**Issue by chadwhitaker** [producthunt/producthunt-api#105]
With my app I'm required to obtain the user's Product Hunt user ID, that way I can make other API calls on their behalf (e.g. `GET /v1/users/<user.id>/votes`).

The only way I'm able to obtain the user's `user.id` is via the `GET /v1/me` endpoint, which only works when your app's scope is set to 'private'.

I'm really trying to stay away from 'private' scope for my app because 1) I don't need/want any of the user's private data/PH settings and 2) any user seeing "access to private data" on the approval screen is grounds for concern.

Would it be possible to quickly update the API so that all apps with 'public' scope can access `/v1/me` which could then return the exact same JSON as `/v1/users/<logged-in-user-id>`?

**Comment by andreasklinger** [comment]
interesting and valid request

but in case of doubt we stick to no-change for the api 

especially we dont want endpoints to behave differently for different scopes in that context

private scope should be fine - you won't be able to write anyhow w/o whitelist - so the bigger risk of abuse would be gone by default
