### ISSUE TITLE
No documentation for oauth#authorize

### ISSUE THREAD

**Issue by dnosk** [producthunt/producthunt-api#106]
This page in documentation now redirects to the main docs: https://api.producthunt.com/v1/docs/oauth_user_authentication/oauth_authorize_ask_for_access_grant_code_on_behalf_of_the_user

Any idea how to get this documentation back?

**Comment by mscoutermarsh** [comment]
@dnosk Weird, thanks. I'm looking into it

**Comment by mscoutermarsh** [comment]
@dnosk Our docs auto generate. For some reason that page didn't generate last time we ran it.

This is what the page says.

```
        <ul>
          <li>You need to redirect your users to this endpoint <br>
              <em>https://api.producthunt.com/v1/oauth/authorize?client_id=[clientid]&redirect_uri=[where shall we redirect to?]&response_type=code&scope=public+private</em></li>
          </li>
          <li>Once they logged into producthunt and gave your app permission we send them back to <em>[redirect_uri]</em> together with an access_grant token as <em>code</em> parameter.</li>
          <li>Use this access_grant in the oauth#token step</li>
        </ul>
```

Sorry, not super easy to read as HTML. I'll try to get it regenerated and deployed soon.

**Comment by dnosk** [comment]
Thanks @mscoutermarsh!!

**Comment by neuling** [comment]
+1! Also just ran into this issue and bugged @andreasklinger on twitter but then found a blog post with the solution before I found this issue.

**Comment by dnosk** [comment]
@neuling can you link the blog post :)

**Comment by neuling** [comment]
sure: https://medium.com/@daniellandy/https-api-producthunt-com-v1-oauth-authorize-client-id-ph-key-redirect-uri-http-3a-2f-6cfcaf381619#.himvqbqre

**Comment by andreasklinger** [comment]
fix for the docs page should go live today

please reopen if this is still an issue
