### ISSUE TITLE
Is there a way to get all time highest rated products through api?

### ISSUE THREAD

**Issue by prathapskp** [producthunt/producthunt-api#108]
We’re trying to build a dynamic leaderboard of all time highest rated products on ProductHunt (similar to this: https://www.yvoschaap.com/producthunt/, but with different date points). We’re hitting the rate limits - is there a way to either increase the limits, or can you recommend a better solution?

**Comment by andreasklinger** [comment]
make sure you delay in between requests or when you hit request limit

900 requests every 15 minutes

you can even this out to one hour (as in 3600 in 1h) but this is where this is throttled

we do not increase rate limits for non commercial partners to avoid bottle necking the api

**Comment by andreasklinger** [comment]
hope that helps a bit - closing - if not feel free to reopen
