### ISSUE TITLE
Sign out to authorize with another social service

### ISSUE THREAD

**Issue by frozenfrost7** [producthunt/producthunt-api#110]
Hello!
I'm currently trying to implement a simple Android client and it is not clear for me how to perform the sign out procedure to sign in later with another social service. 
So, to sign in first time, I perform the following steps. I call a `/v1/oauth/authorize` method with the corresponding arguments to get a grant code (in Android I just start an activity using intent with ACTION_VIEW and http request as an argument). This opens a product hunt login page where I can choose twitter or facebook to login. Finally I'am redirecting to my redirection url with a grant code as a query argument. Great! But what should I do next time if I decide to sign in with Facebook instead of Twitter for example? What api method should I call? If I just call `authorize` method again, it will return me an old grant code without an opportunity to choose the social service.
Sorry if this is not an issue. Seems I just don't fully understand the authorization process using oauth, but hope you will help me with it.

**Comment by andreasklinger** [comment]
our oauth is independent of how the user logged in at product hunt


or differently put 

you redirect to us -> ask for login 
we redirect to fb or twitter -> ask for login
user is logged in here in our place -> we ask the user if he wants your app to have access
if yes -> we redirect back to you

**Comment by andreasklinger** [comment]
hope this helps - feel free to reopen if not
