### ISSUE TITLE
Problem with post by post #

### ISSUE THREAD

**Issue by kamranisbest** [producthunt/producthunt-api#112]
Hi,

   I am facing issue as when i try to query a post using post id it always returns me same post with post number 27317 and some chinese or korean title. Same is for search by url as in that case also it always returns null no matter which post url i may place. Can you please check on that and confirm the issue. Feel free to contact with me for further details.

Thanks :)

**Comment by andreasklinger** [comment]
happy to look into this - can you show me the actual request (excl your token) and the response

**Comment by kamranisbest** [comment]
Hi,

   This is what i am getting : http://ec2-35-160-152-73.us-west-2.compute.amazonaws.com/hunt_new/test.php on any id search and in case of URL search it returns empty and this is library which i am using for my operations : https://github.com/jamstarter/ProductHunt-PHP-library Feel free to contact with me for further details.

Thanks :)

**Comment by andreasklinger** [comment]
This should work now again - please verify and reopen in case it is not working as you expect it to
