### ISSUE TITLE
/v1/posts/all returns empty for some post ids (e.g. newer)

### ISSUE THREAD

**Issue by haktansuren** [producthunt/producthunt-api#113]
To reproduce the problem;
`/v1/posts/all?order=asc&newer=6244`
Result: returned posts array is empty

`/v1/posts/all?order=asc&newer=6262`
Result: it restarts fetching from post_id 6312

**Comment by haktansuren** [comment]
Similar problem for 
`/v1/posts/all?order=asc&newer=84088`

It catches up after `84097 `again...

**Comment by janklimo** [comment]
+1 similar problem for votes:
`/v1/posts/85104/votes?order=asc` returns 50 items, the last vote having id `5889939`. 

Requesting
`/v1/posts/85104/votes?order=asc&newer=5889939` returns only one post, despite post `85104` having 367 votes as I'm writing this.

Thoughts on this, @andreasklinger? A change in the way `newer` behaves seems to have been introduced on Dec 6/7.

**Comment by andreasklinger** [comment]
thx - looking into this today

yes last deployment might intro'd a bug

**Comment by dnosk** [comment]
Same problem for me with following/followers. Older and newer parameters returns empty array

**Comment by andreasklinger** [comment]
thanks - all models use the same logic internally now

pro: 
- centralized a bunch of code
- responses are now significantly smaller (eg empty)

contra:
- responses shouldnt be significantly smaller

**Comment by kamranisbest** [comment]
Hi @andreasklinger  any update about pagination issue.

**Comment by andreasklinger** [comment]
This should work now again - please verify and reopen in case it is not working as you expect it to

**Comment by janklimo** [comment]
@andreasklinger 💯  https://twitter.com/tophuntsdaily/status/809299659135090688 

Thank you, Andreas!
