### ISSUE TITLE
API use

### ISSUE THREAD

**Issue by TiagoApostolo** [producthunt/producthunt-api#115]
Hi! I need to use the api to an iOS app, to show the posts. I didn't understand how can I get access to it. Need some help.

**Comment by andreasklinger** [comment]
@TiagoApostolo 
http://api.producthunt.com/v1/docs should be a good starter
let me know if you have more questions

**Comment by TiagoApostolo** [comment]
andreasklinger, thanks but I didn't get how can I have an access token. I have this: {"error":"unauthorized_oauth","error_description":"Please supply a valid access token. Refer to our api documentation about how to authorize an api request. Please also make sure you require the correct scopes. Eg \"private public\" for to access private endpoints."}'

**Comment by andreasklinger** [comment]
go here:
https://www.producthunt.com/v1/oauth/applications

create an app and a developer token

pick any endpoint from here:
http://api.producthunt.com/v1/docs

eg 

`https://api.producthunt.com/v1/posts/all?search[url]=https://blokdust.com`
this will show you all posts that relate to the url https://blokdust.com

be sure to include these headers:
```
Accept: application/json
Content-Type: application/json
Authorization: Bearer <your developer token from before
```


now you can create a simple html page with a form asking for an URL to check
you server just needs to ping our API and see if there is a response (show the link) or not

**Comment by andreasklinger** [comment]
if you have more questions feel free to reopen

**Comment by TiagoApostolo** [comment]
It is a iOS app, so what should be the redirect URL in "create a application"?

**Comment by shadowTech827** [comment]
Getting the same issue even after providing the developer token in Authorization header
