### ISSUE TITLE
Get arbitrary product by name or PH URL

### ISSUE THREAD

**Issue by pointum** [producthunt/producthunt-api#117]
Looks like there’s no way to get an arbitrary product ID by name or Product Hunt URL.
I wish there was something like /v1/posts/all?search[name] or /v1/posts/all?search[discussion_url] so that a user could search through products by name or pick a product by dropping https://www.producthunt.com/posts/XXX url into my app.
I don’t want to scrap or cache all posts just to get relevant product IDs.
The point of the app is to bookmark posts and get notified of new comments. You don’t provide this useful feature on the website. At this point my app can track my own products through /v1/me/, but I wanted to make the app useful for non-makers as well.

**Comment by mscoutermarsh** [comment]
Hey,

You can retrieve them by `slug` (the url safe name of the product).

Example: https://api.producthunt.com/v1/posts/all?search[slug]=meerkat

Will grab: https://www.producthunt.com/posts/meerkat

Hope that helps 😄

**Comment by pointum** [comment]
Perfect! Thank you. I don't think `[slug]` is ever mentioned in the docs for `posts`.

**Comment by mscoutermarsh** [comment]
🙌
