### ISSUE TITLE
404 on OAuth

### ISSUE THREAD

**Issue by dnosk** [producthunt/producthunt-api#118]
Hey PH!

I am getting a 404 page on a previously working api endpoint for oauth#authorize. I am trying to use the following: 

https://api.producthunt.com/v1/oauth/authorize?client_id=[CLIENT_ID]&redirect_uri=[REDIRECT_ID]&response_type=code&scope=public+private

Is something different? Would love to troubleshoot.

Best,
Dan

**Comment by vesln** [comment]
Thanks Dan! I think I know what caused the issue. I will get back to you once I have a fix for you to test.

**Comment by dnosk** [comment]
Awesome, thanks!
