### ISSUE TITLE
Post ID from URL

### ISSUE THREAD

**Issue by rahulkapoor90** [producthunt/producthunt-api#119]
I happen to have this URL https://www.producthunt.com/posts/slack How do i get the post ID of that url as i am trying to get votes of this product using PH api and using JS.

**Comment by RStankov** [comment]
Hey,

You can retrieve them by `slug` (the url safe name of the product).

Example: https://api.producthunt.com/v1/posts/all?search[slug]=slack

Will grab: https://www.producthunt.com/posts/slack

Hope that helps 😄

**Comment by rahulkapoor90** [comment]
Thanks. for the help.

any idea why i am getting 400 bad request on this?

```
var req = new XMLHttpRequest();
req.onreadystatechange = function() {
  if (req.readyState === 4) {
      if (req.status === 200) {
        var data1 = JSON.parse(req.responseText);
        console.log(data1);
      }
    }
};
var params = "client_id=ADDED_CLIENT_ID&client_secret=ADDED_SECRET_HERE&grant_type=client_credentials";
req.open("POST", "https://api.producthunt.com//v1/oauth/token" , true);
req.setRequestHeader("Accept", "application/json");
req.setRequestHeader("Content-Type", "application/json");
req.send(params);

```
