### ISSUE TITLE
Permission to use PH API in hndigest

### ISSUE THREAD

**Issue by dv** [producthunt/producthunt-api#123]
I run https://hackernewsdigest.com - which does exactly what it says on the tin. I'd like to expand and also include product hunts from the PH API. Since I show ads on my newsletter, this technically is commercial usage I think, and the docs mention I need to request permission for that.

Hence: can I use your API to add product hunts to my daily digest? Thanks!

**Comment by andreasklinger** [comment]
thanks for asking

re api: no worries. feel free to use - awesome product!

**Comment by dv** [comment]
Thanks @andreasklinger!
