### ISSUE TITLE
503 application error

### ISSUE THREAD

**Issue by a-sabaa** [producthunt/producthunt-api#125]
Hi I'm getting randomly a lot of 503 application errors especially when trying to fetch users by id and excluding relationships.

Even the documentation page sometimes randomly breaks
https://api.producthunt.com/v1/docs/users/users_show_exclude_%60relationships%60

**Comment by a-sabaa** [comment]
So basically if I do something like this:

curl -X GET \
  'https://api.producthunt.com/v1/posts/all?sorted_by=created_at&order=asc&per_page=50' \
  -H 'authorization: Bearer INSERT_TOKEN_HERE'

and then run

curl -X GET \
  'https://api.producthunt.com/v1/users/9?exclude%5B%5D=relationships' \
  -H 'authorization: Bearer INSERT_TOKEN_HERE'

10 times..I get the error, then the API is completely messed up for me and starts returning those random 503 errors..

**Comment by mscoutermarsh** [comment]
Hey, @a-sabaa is this still happening? We had an issue that we deployed a fix for last week.
