### ISSUE TITLE
Push Notification Example

### ISSUE THREAD

**Issue by antoaravinth** [producthunt/producthunt-api#126]
Hi,

I’m trying to build a simple Progressive web app using your APIs. I’m looking at the Push Notifications API. The documentation says that I need to pass on "PushService Vendor Token for Browser Push Notification”. I don’t get it, what that mean really. Or how one should get/create it.

If by any chance if you have examples for push notifications it will be really great.

**Comment by antoaravinth** [comment]
Any updates on this?

**Comment by mscoutermarsh** [comment]
Hi @antoaravinth, this is something we use for our official iOS app and shouldn't be in the public docs. Sorry about that!

(we have auto generating docs and these were included by mistake)

**Comment by antoaravinth** [comment]
@mscoutermarsh : Oops! Thanks for the response. Will close the issue!
