### ISSUE TITLE
Issue with my product list

### ISSUE THREAD

**Issue by Ravi-kavya01** [producthunt/producthunt-api#130]
Hyy,
I am calling api to get my post Api link below:
https://api.producthunt.com/v1/users/963905/products
It does not return any data while i have one post and it is working perfect when we use your user given in doc.

Thanks
Ravi Shukla

**Comment by RStankov** [comment]
Hi,

`/products` returns posts the given user is marked as maker. For user with id `963905` - https://www.producthunt.com/@ravi_shukla there no products.

**Comment by Ravi-kavya01** [comment]
As i can see i have one submitted product. Below is the link of my account:
https://www.producthunt.com/@ravi_shukla/submitted

Thanks
Ravi Shukla

**Comment by RStankov** [comment]
`submitted` is product posted by you, while `products` from api is product where you are added as maker.

Here is a table explaining it better:

| PH URL | API Endpoint |
|--|--|
| https://www.producthunt.com/@ravi_shukla/made | `/v1/users/963905/products`
| https://www.producthunt.com/@ravi_shukla/submitted | `/v1/users/963905/posts`

**Comment by Ravi-kavya01** [comment]
I have used new endpoint '/v1/users/963905/posts' as you suggest but still
same problem, not getting any record while i have posted one.

**Comment by RStankov** [comment]
I checked. The problem is `/v1/users/963905/posts` actually returns only featured posts and the post you had was not featured.

**Comment by Ravi-kavya01** [comment]
Then how can i list my post. Is there any api for this.

**Comment by RStankov** [comment]
Not at this moment. :(
