### ISSUE TITLE
I am getting error: access_denied when we submit comment on any post

### ISSUE THREAD

**Issue by Ravi-kavya01** [producthunt/producthunt-api#131]
Hello Team,

I am getting error: access_denied when we submit comment on any post

stdClass Object
(
    [error] => access_denied
    [error_description] => Sorry. You are not allowed to do this. If you suspect this is an error please contact our support team.
    [details] => ErrorHandling::WritePermissions: Your application is not allowed to write data on behalf of the user
)

In my profile information the information is showing that is have permission
[permissions] => stdClass Object
                (
                    [can_vote_posts] => 1
                    [can_comment] => 1
                    [can_post] => 1
                    [can_change_username] => 
                )

**Comment by RStankov** [comment]
Unfortunately at this point the API is read-only, and we don't give out write permissions.
