### ISSUE TITLE
How to get post's `AROUND THE WEB ` links

### ISSUE THREAD

**Issue by ian-patel** [producthunt/producthunt-api#136]
Hi,

I'm trying to get **around the web** links. In the `posts#show` there is an attribute `related_links` but it always returns an empty array.

Any future plan to add those **around the web** links in API?

**Comment by devladinci** [comment]
Hey @ian-patel,  around the web is available now with getting post details `/post/1` attribute name `external_links`

**Comment by ian-patel** [comment]
@devladinci Really appreciate, that helps me a lot. 
I have similar question again. How would I get **Social links** of the product?

Any future plan to add those social links over API?
