### ISSUE TITLE
Is there any api where i can get all comment of a post of a specific user

### ISSUE THREAD

**Issue by Ravi-kavya01** [producthunt/producthunt-api#138]
Is there any api where i can get all comment of a post of a specific user.

Example: If user "Ram" has post 50 post and there are lots of comment.

How can i access all comment of the post by "Ram"

**Comment by RStankov** [comment]
Hi,

You can search for comments by both `post_id` and `user_id`, this is the url you can use:

```
GET /v1/comments?search[user_id]=1&search[post_id]=1
```

More information here:

https://api.producthunt.com/v1/docs/comments_and_comment_threads/comments_index_get_the_latest_comments

**Comment by Ravi-kavya01** [comment]
i am talking about multiple post. In the post_id we can pass only one post_id

**Comment by RStankov** [comment]
oh, my bad. 

You can access all of user comments by calling:

```
GET /v1/comments?search[user_id]=1
```

**Comment by Ravi-kavya01** [comment]
From this api, We can get all comment by user_id.
Ex:
User1 has 5 posts (post1, post2, post3, post4, post5).
Post1 has 20 comments, Post2 has 10 comments etc, 

I want to access all comments post by other users not User1.

**Comment by RStankov** [comment]
We don't support that.

**Comment by Ravi-kavya01** [comment]
Okay thanks
