### ISSUE TITLE
/posts/all only returns featured posts?

### ISSUE THREAD

**Issue by annapowellsmith** [producthunt/producthunt-api#140]
As per [this comment](https://github.com/producthunt/producthunt-api/issues/129#issuecomment-321732324), it seems that `/posts/all` only returns featured posts, though the documentation doesn't mention this. 

Is there any way to get lists of posts that include non-featured ones?

**Comment by RStankov** [comment]
Hi, 

Currently, we don't support fetching of unfeatured posts.
