### ISSUE TITLE
Empty `access-control-expose-headers` prevents access to rate limiting info headers

### ISSUE THREAD

**Issue by cms5x** [producthunt/producthunt-api#141]
Trying to access the rate-limit headers from here: https://api.producthunt.com/v1/docs/rate_limits/headers

But they are not listed in the response to the preflight OPTIONS request.
When they are not listed as exposed, clients cannot access them.

I believe the output of this:
```curl -H "Origin: http://example.com"    -H "Access-Control-Request-Method: GET"    -H "Access-Control-Request-Headers: Authorization"    -X OPTIONS --verbose    https://api.producthunt.com/v1/posts```

should include this:
```access-control-expose-headers: X-Rate-Limit-Limit, X-Rate-Limit-Remaining, X-Rate-Limit-Reset```

**Comment by dhruvparmar372** [comment]
Hey @cms5x we've released new V2 API powered by GraphQL. You should be able to access the Rate Limit headers when using `v2` endpoint. Check here for [docs](https://api.producthunt.com/v2/docs)

Closing this issue as V1 API is deprecated and will be out of support.
