### ISSUE TITLE
Bugs with <pre> tags

### ISSUE THREAD

**Issue by niksib** [producthunt/producthunt-api#142]
When text is too large you have something like this:

![image](https://user-images.githubusercontent.com/13890155/41413429-c2a76310-6feb-11e8-8b88-eb8f325c7300.png)

You cand add somethin like this - `overflow: scroll;` for this class `.p-api-v1-docs .api--content pre` and take this:

![image](https://user-images.githubusercontent.com/13890155/41413519-ffda1250-6feb-11e8-8764-1a29ba074b65.png)

**Comment by RStankov** [comment]
Thanks for reporting 🙌

This is fixed now.
