### ISSUE TITLE
Already hunted or not endpoint

### ISSUE THREAD

**Issue by iamtekeste** [producthunt/producthunt-api#143]
Hi, there I have this really fun idea for the PH community.
I want to build a Chrome extension that tells you if a website is already hunted or not. 
Does PH API have an endpoint for this? If not is there another way I can achieve this?
Thank you in advance!

**Comment by RStankov** [comment]
Hi, @iamtekeste 

This is a great idea 🙌

You can use `posts/all?search[url]=` for this. 
[Here](https://api.producthunt.com/v1/docs/posts/posts_all_find_posts_with_given_url_(eg_to_avoid_duplicates)) are the docs about it:
https://api.producthunt.com/v1/docs/posts/posts_all_find_posts_with_given_url_(eg_to_avoid_duplicates)

**Comment by iamtekeste** [comment]
@RStankov I was able to get this working with the [Client level access token](https://api.producthunt.com/v1/docs/oauth_client_only_authentication/oauth_token_ask_for_client_level_token). 

Does this token ever expire? If yes for how long is it valid? And is there a way to get an access token that never expires?

Thank you for your help!

**Comment by iamtekeste** [comment]
Hi @RStankov It looks the token doesn't expire! 
I have shared my extension on Product Hunt!
https://www.producthunt.com/posts/hunted-or-nah
