### ISSUE TITLE
/v1/me/feed returns empty posts array

### ISSUE THREAD

**Issue by msolomonTMG** [producthunt/producthunt-api#144]
👋I've been using /v1/me/feed endpoint to grab today's latest posts but recently the response has been returning an empty array

The response looks like this:
`{ "posts:" [] }`

**Comment by RStankov** [comment]
Hi, 

`/v1/me/feed` used to return posts from Users feed, we removed that feature. 

You can use `/v1/posts` to get the latest posts for today.

**Comment by msolomonTMG** [comment]
Thanks, that worked! 
I think it might be helpful to others if this documentation was updated to reflect this:
https://api.producthunt.com/v1/docs/posts/posts_index_get_the_tech_posts_of_today
