### ISSUE TITLE
Increase limits for my API application

### ISSUE THREAD

**Issue by niksib** [producthunt/producthunt-api#146]
Hello.
I created the project which is completely dependent on Product Hunt API.
Can you increase limits for my API application(ID - 6131)?

**Comment by RStankov** [comment]
Hi, how many requests are you expecting to have from your app?

**Comment by niksib** [comment]
@RStankov 1500-2000 requests

**Comment by RStankov** [comment]
@niksib are those per hour? Since your current limit is 3000 requests per hour.

**Comment by niksib** [comment]
@RStankov Sorry, I think per 15 minutes = 900 requests (currently), then 6000 I think that's enough

**Comment by RStankov** [comment]
Ok, increasing you limit.

**Comment by niksib** [comment]
Thanks

**Comment by niksib** [comment]
Hello, currently my application has 25 requests per 15 minutes to API.
Why have reduced the number of requests?

**Comment by niksib** [comment]
Already increased :)
