### ISSUE TITLE
Using API Without oauth2

### ISSUE THREAD

**Issue by lweld** [producthunt/producthunt-api#147]
Hi, I'm interested in using the Product Hunt API to chart the types of products launched over time. I just need a bit of information from Product Hunt and my app won't have a user login, so I don't want to go down the oauth2 route. 

I noticed you provide a developer_token in the app dashboard but when I click "Add an application" it asks me for a "Redirect URI", which I assume is the URL of my app. I don't have a URL yet. Any way that I can use the API to simply get data on products' tags?

**Comment by RStankov** [comment]
Hi, 

We provide an RSS feed of recent product launches at https://www.producthunt.com/feed

For all other access, we require `OAuth` access token.
