### ISSUE TITLE
Endpoint to get just the list of top 5 products of the day

### ISSUE THREAD

**Issue by prakis** [producthunt/producthunt-api#150]
Hi there,

Currently https://api.producthunt.com/v1/posts/all returns alot of data. And it is slow (I guess its because it is returning ~450kb data).

Is there a way to just get the top products of the day ?  Something like get me only top-1 product of a particular day? 
get me top second product of a particular day?
get me top third product of a particular day? etc.

Thank you

**Comment by niksib** [comment]
Hello, it already has an API.
Method **posts/all**, with params:
 'sort_by' => 'votes_count',
 'order' => 'desc',
 'per_page' => 5
 'search[featured_year]' => 2018,
 'search[featured_month]' => 11,
 'search[featured_day]' => 12

**Comment by prakis** [comment]
Perfect 'per_page' is what I was looking for.

Thank you @niksib

**Comment by RStankov** [comment]
@niksib Thanks for explaining this 🙌
