### ISSUE TITLE
How to get popular posts

### ISSUE THREAD

**Issue by Ravi-kavya01** [producthunt/producthunt-api#152]
Hello There,

I am trying to access popular post like what product hunt has on his home page.
I tried by sorting with sort_by key with all the possible fields but not able to get the popular record.

Thanks

**Comment by RStankov** [comment]
Hey,

You can use [/v1/posts](https://api.producthunt.com/v1/docs/posts/posts_index_get_the_tech_posts_of_today) - it gets you today top posts. You can also filter for specific [day](https://api.producthunt.com/v1/docs/posts/posts_index_request_a_specific_day_with_the_%60day%60_parameter_(tech_category)).
