### ISSUE TITLE
[Feature Request] Endpoint for Search Posts by Titel

### ISSUE THREAD

**Issue by nimasTT** [producthunt/producthunt-api#153]
I want to find user comments for a search key (for example, "Mobile Game"). There is no way to do this at the moment.
Problem: There is no theme or slug for "Mobile Game".
Searching through the website provides good answers. Is there a way to get the same answers via API? At least the Post Id. Then I could go through the comments in each post.

**Comment by RStankov** [comment]
Hey, we currently don't provide this functionality.
