### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by nimasTT** [producthunt/producthunt-api#154]
Hi, we need for a NLP research user comments on Game Topic. We collect the Data over our Rest Client https://github.com/nimasTT/ProductHuntAPI 
Is it possible to have a higher limitation to get the Data we need? We need the Data just one Time.

Thanks

**Comment by RStankov** [comment]
What is the rate limit you will need?

**Comment by nimasTT** [comment]
It would be enough if you dont throttling our default limit. 
we will analyse the data in many steps. 10-12 Times per Week.

**Comment by RStankov** [comment]
Your current limit is `3600` requests per hour.

**Comment by nimasTT** [comment]
Thanks radoslav,
we have tried it more times in the hour. This hourly Rate is enough. we just have to build a sleep timer in our app.
