### ISSUE TITLE
API seems broken

### ISSUE THREAD

**Issue by Dexwell** [producthunt/producthunt-api#157]
Hey,

So I'm using your OAuth API to let people link up and then show their PH on their profile in my new app.

I'm sending users to:

`https://api.producthunt.com/v1/oauth/authorize?client_id=<CLIENT_ID>&redirect_uri=<URI>&response_type=code&scope=public`

Which redirects to:

`https://api.producthunt.com/v1/login`

The styles aren't loading, and tapping any login link tells me I've found a bug:

![IMG_1450](https://user-images.githubusercontent.com/521176/54914338-076c4180-4ef5-11e9-87f0-dee29fc9a780.jpg)
![IMG_1451](https://user-images.githubusercontent.com/521176/54914342-0a673200-4ef5-11e9-9f7b-29cef5fc27e0.jpg)

**Comment by saraband** [comment]
I don't know if this is related but the link to the [API dashboard](https://api.producthunt.com/v1/oauth/applications) is also down. I was trying to register my application but was unable to do so.

**Comment by dhruvparmar372** [comment]
hey @Dexwell, thanks for reporting the issue. The Twitter authentication flow was misconfigured, I've put in a fix for this. OAuth flow should work as expected now.
