### ISSUE TITLE
Structured API specification

### ISSUE THREAD

**Issue by pimterry** [producthunt/producthunt-api#158]
Is there any kind of structured API specification file somewhere?

OpenAPI/Swagger would be perfect, but anything else too, even if it's just a JSON file you're generating the docs pages from. I'd love to convert whatever it is to OpenAPI, so Product Hunt can join https://github.com/APIs-guru/openapi-directory.

**Comment by dhruvparmar372** [comment]
Hey @pimterry we've released new V2 API powered by GraphQL. You can find [schema.json](https://github.com/producthunt/producthunt-api/blob/master/schema.json) file in the link.

Closing this issue as V1 API is deprecated and will be out of support.
