### ISSUE TITLE
Goals query not found

### ISSUE THREAD

**Issue by niksib** [producthunt/producthunt-api#160]
Hello, I am trying to get my goals, but API explorer can't find any goal connection.

![image](https://user-images.githubusercontent.com/13890155/58074272-8d330300-7bad-11e9-8836-74845e0b7bb3.png)

**Comment by dhruvparmar372** [comment]
hey @niksib, currently `goals` is available as a sub-field inside the `viewer` top level field. You can only fetch the `viewer`'s goals currently. 

Here is a sample query 
```
query ViewerGoals {
  viewer {
    goals {
      edges {
        node {
          title
        }
      }
    }
  }
}
```

**Comment by niksib** [comment]
Hello @dhruvparmar372 
`Viewer` allows getting goals only for the current auth user.
Can I get goals by userId something like this:
```
{
  goal(userId: 123) {
    edges {
      node {
        title
      }
    }
  }
}
```

**Comment by dhruvparmar372** [comment]
As of now it is not possible. We are considering opening other user's `goals` via the API. 
We'll be pushing updates regarding the API here https://www.producthunt.com/makers-festival/product-hunt-api-2-0/discussion/399-api-support

**Comment by niksib** [comment]
@dhruvparmar372 Thanks, waiting for it :)

**Comment by dhruvparmar372** [comment]
@niksib we've added ability to query all `goals` via root query field. check out the documentation for more details http://api-v2-docs.producthunt.com.s3-website-us-east-1.amazonaws.com/operation/query/#goals

**Comment by niksib** [comment]
@dhruvparmar372 Cool, thank you :)
New features for my project is coming 😃
