### ISSUE TITLE
Do you have a plan to add MakerGroups?

### ISSUE THREAD

**Issue by sarunw** [producthunt/producthunt-api#163]
Right now it's impossible to get a list of MakerGroup right?

**Comment by dhruvparmar372** [comment]
Yes, you cannot get list of `MakerGroups` currently. For now there are no plans to add it.

**Comment by dhruvparmar372** [comment]
hey @sarunw we've added ability to fetch `makerGroups` via the root query. check here for more details http://api-v2-docs.producthunt.com.s3-website-us-east-1.amazonaws.com/operation/query/#makergroups
