### ISSUE TITLE
Boilerplate not working [v2]

### ISSUE THREAD

**Issue by nickbae91** [producthunt/producthunt-api#164]
Hi,

I followed your steps exactly and deployed into a heroku server, but nothing is working... I tried debugging and think the app isn't reading the ".env" file...

Any idea what could be wrong? Please lmk if you require any further info.

See deployed app here: https://ph-trendy.herokuapp.com/

**Comment by dhruvparmar372** [comment]
It seems your application is running into an error on startup. 
1. Could you try to tail the logs and post the output here? 
2. Does the app work fine on local machine ? e.g `yarn start` should run without errors.
