### ISSUE TITLE
How to use the developer token

### ISSUE THREAD

**Issue by danbars** [producthunt/producthunt-api#165]
Hello,
I've created a developer token and I try to use it but it gets rejected. 
I put it in Authorization header of my POST request, and I get back this response:
```
{
    "data": null,
    "errors": [
        {
            "error": "invalid_oauth_token",
            "error_description": "Please supply a valid access token. Refer to our api documentation about how to authorize an api request. Please also make sure you require the correct scopes. Eg \"private public\" for to access private endpoints."
        }
    ]
}
```

The request body is a json that looks like this:
`{"query": "{posts {edges {node {id}}}}" }`

I'm just trying to get any query to work. Once I do I will start playing with it.
The URL I'm POSTing to is `https://api.producthunt.com/v2/api/graphql`

Thanks

**Comment by the-alexmeza** [comment]
Are you including Bearer in the value for your authorization header?

i.e. Authorization: Bearer <Developer Token>

**Comment by danbars** [comment]
Yes, I do. 
But now I'm reading the docs again and I see that it says 
"Add the *Authentication* http header with the token to all requests"
I was using *Authorization* header which is the standard.
I will try this later when I'm at the office with that header and see if it works. If it does, it seem like a mistake.

**Comment by dhruvparmar372** [comment]
@danbars thanks for pointing out the issue with documentation. We've put in a fix for same https://api.producthunt.com/v2/docs
