### ISSUE TITLE
How do I request "me" in v2?

### ISSUE THREAD

**Issue by ericbae** [producthunt/producthunt-api#167]
In v1, there was "/me" endpoint, which returns the user given the API access token. What is a proper way of getting this in v2 graphql?

**Comment by dhruvparmar372** [comment]
@ericbae you should be able to request it via the `user` field inside `viewer` field in the query. 

Here is a sample query for the same on the API Explorer
<img width="1280" alt="Screenshot 2019-08-22 at 6 43 47 PM" src="https://user-images.githubusercontent.com/3147651/63517568-d37d6280-c50c-11e9-80fd-6a239fc1a087.png">

You can check out all the supported fields in the API reference here http://api-v2-docs.producthunt.com.s3-website-us-east-1.amazonaws.com/object/viewer/#user

**Comment by ericbae** [comment]
Awesome. Thank you.
