### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by adamleo** [producthunt/producthunt-api#171]
Hi there,

I'm trying to use the producthunt api, however there's an issue that I couldn't find any answer to.

getting **access token** was successful, but when I was trying out the query as instructed [here](https://api.producthunt.com/v2/docs/oauth_client_only_authentication/oauth_test_use_the_client_level_token_for_read_api_access), there was no success.

The error msg I got is:
```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```

returned as a response body.

can anyone provide some info on this?

thanks a lot!

**Comment by RStankov** [comment]
Do you still get this error?
