### ISSUE TITLE
Can't connect to api

### ISSUE THREAD

**Issue by Paulo-Sheetgo** [producthunt/producthunt-api#176]
I tried to make requests for API, but it is not possible, can you help me?

url = 'https://www.api.producthunt.com/v2/api/graphql'
    data = {
        'query':'query {viewer {user { testuser }}}'
    }
    headers = {
        'Accept': 'application/json',
        'Content-Type':'application/json',
        'Host': 'api.producthunt.com',
        'Authorization': 'Bearer '+token
    }
    try:
        response = requests.post(url,data=body,headers=headers)
    except Exception as e:
       return e
    return  json.dumps(response)

**Comment by RStankov** [comment]
Hey,

What error do you get?

From what I can see the query `user { testuser }` is invalid, because we don't have `testuser` field on user.

**Comment by Paulo-Sheetgo** [comment]
I think my HTTP call is probably wrong, do you have any functional example?

**Comment by Paulo-Sheetgo** [comment]
Here is a new test, the query worked on the API Explorer, but didn't on the python backend.

def apiProductHunt(id):
    url = 'https://www.api.producthunt.com/v2/api/graphql'
    data = {
        "query":"query {post(id:'amazon-go'){votesCount}}"
    }

    headers = {
        'Accept': 'application/json',
        'Content-Type':'application/json',
        'Authorization': 'Bearer {my_developer_token}',
        'Host': 'api.producthunt.com'
    }
    try:
        response = requests.post(url,data=data,headers=headers)
    except Exception as e:
       return e
    return  json.dumps(response)



The error -  MaxRetryError("HTTPSConnectionPool(host='www.api.producthunt.com', port=443): Max retries exceeded with url: /v2/api/graphql (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f4b03d12828>: Failed to establish a new connection: [Errno -2] Name or service not known',))",)
