### ISSUE TITLE
How to vote for a post?

### ISSUE THREAD

**Issue by xuhong** [producthunt/producthunt-api#178]
Hi, I'm building a ProductHunt client in Wechat, but I didn't found mutation for voting a post in the schema, which is essential for a client, How can I do that?

**Comment by RStankov** [comment]
We don't allow voting via the API.

**Comment by xuhong** [comment]
Is there any possible to build a official ProductHunt client which is able to use the voting api? Producthunt website is hard to access in Chinese network, if there is a client in Wechat mini programe(runs like React-Native), it will improve the user experience a lot, and will help ProductHunt to expand Chinese market. 

I'm glad to help if your are insterested!

**Comment by RStankov** [comment]
I see. Unfortunately it isn't possible at the moment. We bring this up next time we talk about improvements to the API.
