### ISSUE TITLE
Circular dependency [GraphQL]

### ISSUE THREAD

**Issue by own2pwn** [producthunt/producthunt-api#181]
Hi, using [this](https://github.com/caffeinetv/CaffQL) tool I'm unable to generate schema interface for c++. Is there really a dependency cycle in schema or the problem with the tool itself?

**Comment by own2pwn** [comment]
Also, looks like users cant set issue tag by their own(e.g., I'm unable to mark this issue with `v2` label)

**Comment by RStankov** [comment]
It looks like problem with the tool itself. There are not issues with Apollo Codegen.
