### ISSUE TITLE
videoUrl is coming back empty

### ISSUE THREAD

**Issue by francovg** [producthunt/producthunt-api#183]
Hi, I am using the API and I can get most of the results, but when retrieving "videoUrl" and "Makers" the results are always empty.

**Comment by francovg** [comment]
And I made sure that the posts have actually videos.

**Comment by RStankov** [comment]
Hey, can you give me an example of product which had video on the website and return null in api.

**Comment by francovg** [comment]
Thanks, I am receiving null everywhere for "videoUrl" , for example https://www.webflow.com/cms/  https://www.artify.co/     https://artboard.studio/  I tried with many none of them retry the Video url, even though they have one on the PH post.

{
  "data": {
    "posts": {
      "edges": [
        {
          "cursor": "MQ==",
          "node": {
            "id": "35501",
            "createdAt": "2015-10-07T11:51:06Z",
            "makers": [],
            "name": "Webflow CMS",
            "tagline": "Build professional dynamic websites without any code",
            "description": "Create the content structure you need, add content by hand, import it from a CSV, or via the API, then design it visually. Finally, a content management system that works for editors, designers, and developers.",
            "url": "https://www.producthunt.com/posts/webflow-cms-2?utm_campaign=producthunt-api&utm_medium=api-v2&utm_source=Application%3A+PH+API+Explorer+%28ID%3A+9162%29",
            "votesCount": 1697,
            "media": [
              {
                "type": "image",
                "videoUrl": null

**Comment by dhruvparmar372** [comment]
Hey @francovg 
I'm trying out the API via explorer here https://ph-graph-api-explorer.herokuapp.com/

It seems to return the `videoUrl` for the "Webflow CMS" post https://www.producthunt.com/posts/webflow-cms-2

<img width="1281" alt="Screenshot 2020-05-28 at 8 37 40 PM" src="https://user-images.githubusercontent.com/3147651/83159074-3991b880-a123-11ea-8793-682a85da9d5c.png">

The `videoUrl` field is only populated when the media objects have a video url. Could you share the exact query you are running to get the above results ?

**Comment by francovg** [comment]
Hi - thank you for your previous reply! We are now working on implementing
this using a two-step process: 1. fetch id by url, like so: ``` query
{ posts(url:
"https://webflow.com/cms
<https://www.codementor.io/redirect-notice?url=https%3A%2F%2Fwebflow.com%2Fcms>")
{ edges { node { id } } } } ``` 2. fetch all relevant data by id: ``` query
{ post(id: 282222) { id name } } ``` Sadly, step #1 does not yield the
correct id. Can you show us how to get a post id from a URL? Here are two
failing examples: 1. `posts(url: "https://webflow.com/cms")`
<https://www.codementor.io/redirect-notice?url=https%3A%2F%2Fwebflow.com%2Fcms%22)%60>
In
your example, you used `id: 36161`, which refers to the webflow CMS
post. However,
this url query yields three ids, one repeated (35501, 217950, 35501), where
none of them is the id that you showed us (i.e. 36161). 2. `posts(url: "
https://sablecard.com")`
<https://www.codementor.io/redirect-notice?url=https%3A%2F%2Fsablecard.com%22)%60>
This
yields id = `282222`. If we plug that back into the post query (i.e.
`post(id: 282222)`), `data` contains `"post": null` How can we query the
correct id by URL?

**Comment by francovg** [comment]
Hi - thank you for your previous reply!

We are now working on implementing this using a two-step process:

1. fetch id by url, like so:
```
query {
  posts(url: "https://webflow.com/cms") {
    edges {
      node {
        id
      }
    }
  }
}
```

2. fetch all relevant data by id:
```
  query {
    post(id: 282222) {
      id
      name
    }
  }
```



Sadly, step #1 does not yield the correct id. Can you show us how to get a post id from a URL?


Here are two failing examples:

1. `posts(url: "https://webflow.com/cms")`
In your example, you used `id: 36161`, which refers to the webflow CMS post.

However, this url query yields three ids, one repeated (35501, 217950, 35501), where none of them is the id that you showed us (i.e. 36161).


2. `posts(url: "https://sablecard.com")`
This yields id = `282222`. If we plug that back into the post query (i.e. `post(id: 282222)`), `data` contains `"post": null`

How can we query the correct id by URL?

**Comment by francovg** [comment]
Hi @RStankov and @dhruvparmar372 can you please help me with my previous question?, esentially how can we get the ID using the website URL, example https://webflow.com/cms   and getting the product hunt ID.

**Comment by RStankov** [comment]
@francovg I found the issue. Will be working on fix. the `id` is wrong. For now there is a work around - use `slug` instead of `id`.

One question - Why you do 2 queries? In `GraphQL` you can combine them.

**Comment by francovg** [comment]
@RStankov Thanks!, that helped.
