### ISSUE TITLE
API v1: Rate-Limit exceeded

### ISSUE THREAD

**Issue by benjaminsuch** [producthunt/producthunt-api#186]
I wrote a script which helps my colleagues find friends on PH using their exported contacts on LinkedIn (I hope this script doesn't violate any terms). I found out now that the two founders of the startup have over 1000 contacts (I didn't know that is possible...) on LinkedIn.

As you can imagine, the rate-limit is exceeded pretty fast, so my question is if you can increase it or give me a tip, what I can do.

Right now I'm querying https://api.producthunt.com/v1/users/${name}?exclude=relationships

**Comment by RStankov** [comment]
Hey, 

This is an interesting use-case :)

We can't increase your limits at this point.

Try adding a cache layer in your script. So you don't hit the API for every username.
