### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by marshallino16** [producthunt/producthunt-api#189]
Hi, 

I'm building a SwiftUI + Combine macOS app to browse Product Hunt posts and the rate limit is too low. 
Would it be possible to increase it?

Thanks

**Comment by RStankov** [comment]
Hey, what rate limit do you expect you will need?

**Comment by mgautam80** [comment]
Hi,

I have a similar issue. I am using a dev token (its under Cole Grolmus) and call the v2 api to browse upvotes. Would be possible to bump up my limit to about 10 api calls/min? Thanks

**Comment by RStankov** [comment]
@mgautam80 for v2 we don't limit by api calls, we budget based on how complex the queries are. You can do 100k very simple queries or 1 very complex. What is the query you need to limit to ~10 api call/min?

**Comment by mgautam80** [comment]
@RStankov thanks for the quick reply. That makes a lot of sense now. Here is the query. If 10 is too much given the size of this query, i can build in a time delay to try every 30s or even 1 min. Please let me know.
query
            {{
              post(id: "{app_id}") {{
                votes(after: "{end_cursor}") {{
                  totalCount
                  edges {{
                    node {{
                      id
                      user {{
                        name
                        twitterUsername
                        username
                        votedPosts {{
                          edges {{
                            node {{
                              name
                              url
                            }}
                          }}
                        }}
                        createdAt
                      }}
                    }}
                    cursor
                  }}
                  pageInfo {{
                    endCursor
                    hasNextPage
                  }}
                }}
              }}
            }}

**Comment by marcelo-ventura** [comment]
Hey I'm facing the same issue. Is there any update on the subject? @RStankov

**Comment by RStankov** [comment]
Hey, the budget is fix and based on query complexity. @marcelo-ventura  What is the query you have?

**Comment by marcelo-ventura** [comment]
This one @RStankov 
`{
  posts(postedAfter: "%s",
        postedBefore: "%s"){
      edges {
       node {
        id
        name
        votesCount
        createdAt
        featuredAt
        description
        website
        thumbnail {
          url
        }
        media {
          type
          url
        }
      }
    }
  }
}`

**Comment by RStankov** [comment]
How often do you make this query?

**Comment by marcelo-ventura** [comment]
I've parallelized my code to make 4 queries per second but the limit reach was very fast (I was able to make 20 queries).
Then I've included a time sleep of 60 seconds and can make one query per minute.
I've tried to increase my time interval (postedBefore - postedAfter) but every query returns only 20 rows.

**Comment by luckyace** [comment]
@RStankov Hi. Looks like something goes totally wrong with rate limits.
For example, I tried this simple query: 
  posts {
    edges {
      cursor
      node {
       name
       id
      }
    }
  }

And I got successful response with that limits in headers:
x-rate-limit-limit: 25
x-rate-limit-remaining: 25
x-rate-limit-reset: 900

But the same query I tried few seconds later got rejected, and the headers were:
x-rate-limit-limit: 25
x-rate-limit-remaining: -40
x-rate-limit-reset: 828

**Comment by RStankov** [comment]
@marcelo-ventura this is the limit we have. Which is you app? I can try to increase.

**Comment by RStankov** [comment]
@luckyace which is your app which have this results? Will check

**Comment by bijenpatel** [comment]
Hello @RStankov,

I have a relevant question about the rate limit. I am building an analytics app. I wanted to confirm if it is OK to hit the maximum rate limit every 15 minutes? I anticipate needing to acquire pretty big data to build what I have in mind. I think I will need to be constantly hitting the rate limit until I've finished requesting the old historical data for the application. It may take 2-4 weeks. Afterwards, it shouldn't be that much. I'll be using the v1 API, and then transitioning to use the v2 API later. I just wanted to confirm that this will be fine for "fair use" of the API?

Thanks

**Comment by RStankov** [comment]
@bijenpatel if it is for 3-4 weeks it is okay. One thing you have to keep in mind is that we use cloudflair and they have DDOS protection and if you hit this your whole IP might be blocked for longer.
