### ISSUE TITLE
Website and URL in graphql returns same link

### ISSUE THREAD

**Issue by atnac** [producthunt/producthunt-api#192]
Website and URL in graphql returns same link and it is the link for the post, not the actual website link you would see in the product hunt page. 

{
  posts {
    edges {
      node {
        name
        votesCount
        commentsCount
        tagline
        website
        url
      }
    }
  }

Result
          "website": "https://www.producthunt.com/r/48d4bc81b55f05?utm_campaign=producthunt-api&utm_medium=api-v2&utm_source=Application%3A+PH+API+Explorer+%28ID%3A+9162%29",
            "url": "https://www.producthunt.com/posts/catcode?utm_campaign=producthunt-api&utm_medium=api-v2&utm_source=Application%3A+PH+API+Explorer+%28ID%3A+9162%29"

**Comment by RStankov** [comment]
Those two links don't go to the same page.

1. **website** is the the short url to the product website. It redirects to the product website.
2. **url** is product hunt post page url for the post

**Comment by jakobgreenfeld** [comment]
I created a [python script](https://gist.github.com/jakobgreenfeld/75d8382d0c0256ecc52cbb09a1d8b97e) that resolves the shortened url.
