### ISSUE TITLE
Constant 503 Error and ranking question

### ISSUE THREAD

**Issue by Ash110** [producthunt/producthunt-api#194]
Hello,

I've been trying to develop an Android app with the Product Hunt API and I constantly face a 503 error, at least twice per hour. Not sure what the reason is, but any API request returns 503, and so does just visiting https://api.producthunt.com/v2/docs

Secondly, I was wondering how I could get the top posts of previous days using the API. I was trying it with postedBefore and postedAfter to limit the posts to ones posted in that one-day duration, but the order I receive them is slightly different from the order on the website. Is there any other way I can get the top posts of any given date?

Finally, I was hoping I could add In-App purchases in my app to enable dark mode and stuff. Is this against your ToS? Can I do that? 

Thanks!

**Comment by RStankov** [comment]
Hey

* will investigate the 503. We are changing services and this might cause this
* the way to get the post is `postedAfter` will check for the order
* it is fine to charge for dark mode
