### ISSUE TITLE
Cannot Create Goal From my application

### ISSUE THREAD

**Issue by marvinhosea** [producthunt/producthunt-api#195]
I am not able to create a goal from my application yet i can create a goal on ProductHunt Graphiql explorer. Here is the response I get

``` 
{
  "data": {
    "goalCreate": {
      "node": null
    }
  }
}
```

**Comment by RStankov** [comment]
Can you send me the full response and can you add `errors { field message }`?

**Comment by marvinhosea** [comment]
There is no error response. This is the response I am getting when I try to create or update a goal
```
{
  "data": {
    "goalCreate": {
      "node": null
    }
  }
}
```
But when I try on Product Hunt Graphql explorer everything is working well.

I am able to retrieve data but am not able to post/patch/update data. All mutation endpoints are not updating.
And finally, how do I get my application approved(somehow I think that's the reason behind the above error)

**Comment by RStankov** [comment]
What is your PH account?

**Comment by marvinhosea** [comment]
Here is my ProductHunt account https://www.producthunt.com/@marvin_collins

**Comment by RStankov** [comment]
You should be able to write now.
