### ISSUE TITLE
Requesting write access for mutations

### ISSUE THREAD

**Issue by Ash110** [producthunt/producthunt-api#196]
Hello,

I'd like to request write access for Mutations, to allow users to follow and unfollow other users in my app built on the API. I was told to raise an issue here.

Also, I was curious about what the API Rate Limit was. Should I release the app to production, I wouldn't want that to be an issue. If there any way I can get the rate increased after you check out the app or so?

Thanks

**Comment by RStankov** [comment]
Hey, you should be able to have follow/unfollow users via API. For the rate limit, depends on the frequency and contents of the queries.

**Comment by Ash110** [comment]
Maybe I'm doing it wrong
My query is 
`mutation {
    userFollow(input : {
        clientMutationId : <mutationID>, 
        userId:<User ID>,
    }
    ){ 
    clientMutationId
    errors{
        field
        message
    }
    node{
        id
        name
    }
    }
}`

And the response I get is 
`
{
    "data": {
        "userFollow": {
            "clientMutationId": <Mutation ID>,
            "errors": [
                {
                    "field": "base",
                    "message": "Your application does not have write access enabled. Please contact hello@producthunt.com with your API Key."
                }
            ],
            "node": null
        }
    }
}
`

**Comment by marvinhosea** [comment]
I am experiencing the same thing I am not able to update any mutation endpoints even when i use my own developer token

**Comment by RStankov** [comment]
What your PH accounts?

**Comment by Ash110** [comment]
ashwin.alaparthi@gmail.com

**Comment by RStankov** [comment]
@Ash110  you should have write access and increased your api limit.

**Comment by HermanKayy** [comment]
@RStankov Hello I'm creating a Product Hunt client and would love to get a rate limit increase + write access as well!

**Comment by RStankov** [comment]
Hey, @hereisnaman 

1. What do you need the write access for? - follow or goals?
2. How much you want the rate limit to be increased by?

**Comment by HermanKayy** [comment]
@RStankov 
1. I would love write access to be able to follow posts and potentially comment on posts as well
2. Currently I'm constantly running out since I do a fetch on the current posts with pagination. Also whenever they select a topic to show a list of posts and pagination. As you can see thats quite a lot of queries. I would love to increase it by double/triple if possible for the testing period as I'm building out the product

**Comment by RStankov** [comment]
Ok, will increase you limit rate budget. We don't provide API for creating comments. What does follow post means?

**Comment by HermanKayy** [comment]
@RStankov Ahh I see didn't know that that's a shame. Is there docs on what write access I can get? Sorry I meant follow user not follow post, typo on my end

**Comment by RStankov** [comment]
@HermanKayy  Here we have all mutations in write access:

http://api-v2-docs.producthunt.com.s3-website-us-east-1.amazonaws.com/operation/mutation/

* goalCheer
* goalCheerUndo
* goalCreate
* goalMarkAsComplete
* goalMarkAsIncomplete
* goalUpdate
* userFollow
* userFollowUndo

**Comment by HermanKayy** [comment]
@RStankov I see okay thank you.  Seems the current Product Hunt iOS app has a Comment UI, but doesn't actually do anything when you hit send. Looking forward to be able to post Comments hopefully in the future!

**Comment by RStankov** [comment]
@rajasimon you can `userFollow` / `userFollowUndo` in v2 API.

**Comment by rajasimon** [comment]
@RStankov I thought you granted me the permission but just now checked I don't have the access. 

Can you give me access again ? 

```
{'userFollow': {'clientMutationId': 'dontknowthis', 'errors': [{'field': 'base', 'message': 'Your application does not have write access enabled. Please contact hello@producthunt.com with your API Key.'}], 'node': None}}

```

**Comment by rajasimon** [comment]
@RStankov Can you double-check  I've `userFollow/userFollowUndo` permission on my account, please?
