### ISSUE TITLE
Rate Limit Increase Request

### ISSUE THREAD

**Issue by Ash110** [producthunt/producthunt-api#197]
Hello, 

I'm making a Product Hunt client using the API v2 and would like an increase in the rate limit. I make queries where I have to fetch the top posts currently and when a post is opened get the details of the post, the maker, the comments and details of the commenter and so on. This makes for a fairly complex query which uses up a lot of the rate limit. Could this be increased before I put this app out on production. I'm not sure how to measure what rate limit I would need.

Thanks

**Comment by RStankov** [comment]
Which is your user account? I'll update your rate limit.

**Comment by Ash110** [comment]
The app is called Huntr and the email is ashwin.alaparthi@gmail.com

**Comment by RStankov** [comment]
Resolved as #196
