### ISSUE TITLE
Order Aphabetically?

### ISSUE THREAD

**Issue by HermanKayy** [producthunt/producthunt-api#198]
Hello PH Team! Looking through the docs I noticed you can fetch by newest or by followers count. Is there a way we can do this alphabetically?

**Comment by HermanKayy** [comment]
I wanted to clarify this is for Topics

**Comment by RStankov** [comment]
We don't have this at the moment due to performance reasons.

**Comment by HermanKayy** [comment]
Okay thank you @RStankov
