### ISSUE TITLE
Write access to API

### ISSUE THREAD

**Issue by sasacocic** [producthunt/producthunt-api#199]
I have an application I'd like to build, and it requires write access to the producthunt-api.

I've gone through, and read the docs at: https://api.producthunt.com/v2/docs

I've contacted hello@producthunt.com to ask for write permissions. They directed me here in order to get write access to the API.

Any help appreciated. Thanks.

**Comment by RStankov** [comment]
Hey, can you share more information about the app. Which APIs it is going to use?

**Comment by sasacocic** [comment]
I'm only familiar with one API (graphql) which is the one I mentioned: https://api.producthunt.com/v2/docs

The app only needs write access for apps `Posts`. Basically I would like to allow creating of `Posts` further out than 1 week.

The app allow users to set

**Comment by RStankov** [comment]
We can't create posts via the API. The main reason for this, we change the format of post submissions frequently and exposed as public API will make it harder for us to do this.
