### ISSUE TITLE
Incorrect RANKING query

### ISSUE THREAD

**Issue by HermanKayy** [producthunt/producthunt-api#200]
Hello I have the below query and the response I receive is in a different order than what I'm seeing on the Product Hunt website. Am I doing something wrong?

**Query**

`{
  query: posts(first: 100, topic: "apis", order:FEATURED_AT) {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      cursor
      node {
        id
        name
        createdAt
      }
    }
  }
}`

On product hunt website I clicked on Topics -> APIS -> Sort by Trending, and the order of that is different than my response

**Comment by HermanKayy** [comment]
Is this because I'm using the v2 graphql api and perhaps the product hunt website is using V1?

**Comment by RStankov** [comment]
Hey, for getting homepage ranking you should use `RANKING` order. Currently we have the following ordering options:

* 'FEATURED_AT' - Returns Posts in descending order of featured date.
* 'RANKING' - Returns Posts in descending order of ranking.
* 'NEWEST' - Returns Posts in descending order of creation date.

**Comment by HermanKayy** [comment]
Hi @RStankov , I used `RANKING` and I do get a response back. The issue is the order I get back is not the same order as what i'm seeing in ProductHunt.com . The order is slightly different

**Comment by RStankov** [comment]
I'll check, order should be the same.
