### ISSUE TITLE
Random 503 Error on a Daily basis

### ISSUE THREAD

**Issue by HermanKayy** [producthunt/producthunt-api#202]
Hello Product Hunt team!

I've experienced 503 Service Temporary Unavailable randomly sometimes throughout the day and then after a couple of minutes it'll start working again on the V2 API without changing anything on my end. This happens at least 3-4 times a day everyday so far. I've attached some screenshots below and please let me know if you need any additional info to help you debug.

### Postman Screenshot:

<img width="608" alt="Screen Shot 2020-12-13 at 8 05 02 PM" src="https://user-images.githubusercontent.com/32886440/102039521-f32e3f00-3d7e-11eb-8d00-a0a1da35aee6.png">

### Product Hunt Api Docs

<img width="814" alt="Screen Shot 2020-12-13 at 8 05 54 PM" src="https://user-images.githubusercontent.com/32886440/102039543-06410f00-3d7f-11eb-990c-47ee53b15701.png">

### Product Hunt Graphql Explorer

<img width="608" alt="Screen Shot 2020-12-13 at 8 05 07 PM" src="https://user-images.githubusercontent.com/32886440/102039554-0f31e080-3d7f-11eb-843d-c933a9dc2343.png">

**Comment by RStankov** [comment]
Hey, we are changing some backend services the last week, which might have caused this. When does it started happing?

**Comment by HermanKayy** [comment]
@RStankov Ahh it was about a week ago so that might explain it. Are you guys currently still changing the backend services? I can keep an eye out but it occurred this week so far as well about 3-4 times daily

**Comment by RStankov** [comment]
We are in the process of moving services and adjusting auto scaling. We might need to increase the API thresholds
