### ISSUE TITLE
V1 Deprecation?

### ISSUE THREAD

**Issue by HermanKayy** [producthunt/producthunt-api#204]
I’m integrating the v2 api atm for an ios app I’m building. There are many features on the v1 api thats not currently supported for the v2 api for example commenting on posts.

On the api docs it says V1 api is being deprecated when is it going to be no longer supported? Can I still use v1 since it has more stuff provided?

**Comment by RStankov** [comment]
Hey, 

We are going to support v1 for at least another year.

Which features from v1 are you missing?

**Comment by HermanKayy** [comment]
@RStankov Being able to write comments on V2 API seems like you can only read comments atm on v2 but not write access

**Comment by RStankov** [comment]
We stop giving comment write access in V1 long time ago (due to misuse of the API) and we don't have plans to support comment creation in V2.
