### ISSUE TITLE
Query for a specific user # number

### ISSUE THREAD

**Issue by akinhwan** [producthunt/producthunt-api#205]
Hello,

I was wondering if it is possible to query for a specific user #

for example I'd like to find user #222222
I would only query like this 10 times, so it would not at all be regular or spammy.

**Comment by RStankov** [comment]
Hey, you can query user by id:

```
query {
  user(id: "222222") {
    name
  }
}
```

[More info](http://api-v2-docs.producthunt.com.s3-website-us-east-1.amazonaws.com/operation/query/#user)
