### ISSUE TITLE
Rate limit increase

### ISSUE THREAD

**Issue by luiseeisfeld** [producthunt/producthunt-api#206]
Hello,
I would like to know if it is possible to increase the rate limit of the API? 
I am a PhD student in Economics, and trying to fetch data from Product Hunt for a project I'm working on. A rate limit increase would really help me advance the project. Thanks a lot!

**Comment by RStankov** [comment]
Hey, 

What is your PH username?
How much do you need your limit increased by?

**Comment by luiseeisfeld** [comment]
Username is luise_e (#2766954)

It would be great if the rate limit could be increased by at least 3 times the current rate... (maybe even 5 times the current rate, if possible), but I don't know if that is too much to ask? 
Just to be sure, I am not building an app. I'm planning to use the API for fetching data in the next weeks, and that is it.

Thank you!

**Comment by RStankov** [comment]
:+1: Increased the limit, hope it is enough.

**Comment by luiseeisfeld** [comment]
Hi,
Since a bit more than 24 hours, I keep running into a "Too Many Requests (HTTP 429)" Error much sooner than usual.
I am wondering, was my rate limit increase reversed, or is this a temporal decrease? Is there a way to increase it again?
Thanks a lot in advance!
Best regards
Luise

**Comment by RStankov** [comment]
We haven't done any changes to rate-limiting recently and your account still have same params as 18 days ago.

**Comment by luiseeisfeld** [comment]
Okay, thanks a lot for checking!
