### ISSUE TITLE
Way to fetch posts by multiple topics? 

### ISSUE THREAD

**Issue by ShubhamVerma1811** [producthunt/producthunt-api#208]
Hey, so I was trying out your API on the explorer.

I am looking a way to get posts that contain multiple topics

{
// I can only fetch posts of one topics,way to fetch by multiple topics?
posts(topic: "tech") { 
edges {
node {
name
url
}
}
}
}

And would I be needing an access token to use this API?

**Comment by RStankov** [comment]
Hey, currently we support only fetching post with single topic.

You will need access key to access the API.

**Comment by ShubhamVerma1811** [comment]
I got the developer token
I tried passing it as Breaker token in Postman but it said invalid token.
Which auth type should I pass the token to?
