### ISSUE TITLE
Caching the apis in cdn level

### ISSUE THREAD

**Issue by subhendukundu** [producthunt/producthunt-api#212]
I am building an app with Producthunt APIs. I love the documentation.
But there's one thing kinda stuck in my mind is, the response time. I see for 
```
query posts {
  posts {
    edges{
      node {
        id
        name
        description
        media {
          videoUrl
        }
      }
    }
  }
}
```
this query takes at least 1.5-2secs.

Questions,
1. As the data doesn't change in every 30 mins, would it make sense to cache them in the CDN level?
2. How long the access_token is valid for the application level, not logging the user in?
3. Is there a way to get an expiry time of the token? So that I can refresh the token.

Meanwhile, Can I get an increase in the rate limit for my username `thisissubhendu`? I am not sure, how much increase I need at the moment. :(

**Comment by RStankov** [comment]
1.  Unfortunately GraphQL being cached on CDN is not very easy. Better solution is to implement cache at app level, this will reduce the API requests like this?
2. This tokens don't expire
3. Can you implement app level cache to reduce request? Can you give more context about the app and how much of API will use

**Comment by subhendukundu** [comment]
1. True, it's not easy but not impossible. I just finxed a demo example for you, I figured you would say this 🙈
Try `https://graphql.daku.app`

Not client-level caching, but CDN level.

To see it in actions,

```
makers {
  id
  name
  username
}
```
add this, you will see response time 2s and after that it will under 30ms.

for another example, you can add this one too.

```
user{
  name
  username
}
```

```
query posts {
  posts {
    edges{
      node {
        id
        name
        description
        website
        slug
        thumbnail {
          videoUrl
          url
        }
        media {
          videoUrl
          url
        }
        makers {
          id
          name
          username
        }
        user{
          name
          username
        }
      }
    }
  }
}

```

2. Awesome!
3. I always wanted to make an app that would just let me scroll through different new products. It might sound weird but I get amazed with people's creativity. And I love that. Later this year I came across Producthunt. It does exactly that.

Tho I really couldn't trash out making my own Producthunt from my mind. And it wouldn't make sense to make another Producthunt. So I ended up making https://daku.app. It has android and iOS apps as well. On a side note, Daku is a Sanskrit word, which means "robbers" somewhat.

I am using Producthunt API to show the products and it sends the user back to Producthunt if they like the product. Basically, Daku is just a fun app to use Producthunt like Tinder in a nutshell.


PS: I might not need the increase, cause I am caching it for 30mins for requests. :)

**Comment by RStankov** [comment]
@subhendukundu  This is great. I will increase your limit just in case ;)

**Comment by subhendukundu** [comment]
Hey @RStankov 
I have started getting `"message": "Query has complexity of 1262, which exceeds max complexity of 1000"`
Do you think you can increase the limit to ~2000? 🙏🙏

**Comment by RStankov** [comment]
@subhendukundu complexity is separate from rate limit. It defines how much computation a single query can have. Having queries with large complexity, hogs the whole server down.
