### ISSUE TITLE
Get all ProductHunt posts of today

### ISSUE THREAD

**Issue by petkoqnev** [producthunt/producthunt-api#215]
I'm trying to get all Producthunt posts of today. I'm not a developer so this is a bit more technical for me. 
At the moment I'm using https://api.producthunt.com/v1/posts/all but don't know the right parameters to achieve this.
I'd like to pull the new posts everyday. What is the right API endpoint with all parameters to achieve this?

**Comment by petkoqnev** [comment]
I've read this one - http://api-v2-docs.producthunt.com.s3-website-us-east-1.amazonaws.com/operation/query/#posts
And I'm wondering can I achieve what I want with:
https://api.producthunt.com/v1/posts/all?order=NEWEST
+ maybe limiting the number of posts to a certain number per day as to avoid duplicates?
Do you think this can work?

**Comment by RStankov** [comment]
Hey,

You can use [post](http://api-v2-docs.producthunt.com.s3-website-us-east-1.amazonaws.com/operation/query/#posts) field in APIv2

```graphql
posts(featured: false, postedBefore: $theDayAfter, first: 20, after: $cursor) {
  edges { ... }
  pageInfo  {
    hasNextPage
    endCursor
  }
}
```

This is paginated, so you might need to check
