### ISSUE TITLE
Question about API Usage

### ISSUE THREAD

**Issue by asanjeevrao** [producthunt/producthunt-api#216]
Hello PH Devs,

I'm the founder of Hoist (http://tryhoist.com/). I had a quick question about the Product Hunt API Usage. I reached out on email first but was asked to create an issue here. 

Hoist helps businesses aggregate social proof across different platforms into one shareable wall. We also make it easy to collect video testimonials.

We want to build a feature where users can add their Product Hunt post URL through the Hoist web app and it would fetch all first-level comments on the post as individual 'tiles'. The user can filter these tiles and import & publish a select few to their live wall (example of a live wall here -https://app.tryhoist.com/w/betterhabitsdemo). Essentially we're trying to make it easy for founders to showcase the social proof they've generated through Product Hunt.

Wanted to check if this usage is permitted. Given your requirements, we can include it in our free pricing tier. So no user would ever have to pay for using this feature.

**Comment by RStankov** [comment]
Hey, yes this usage is allowed :)
