### ISSUE TITLE
Does pusher subscription work?

### ISSUE THREAD

**Issue by jeremyrajan** [producthunt/producthunt-api#227]
Hi,

I tried getting the new posts as per the README example. But I didn't get any events triggered. Is it working?

```javascript
const pusher = new Pusher('7c1db8905b12d9aa6a03');

    const phChannel = pusher.subscribe('ph-posts');

    // Listen for new posts
    phChannel.bind('new-post', function (post) {
      // Output post to the browser console
      console.log(post);
    });
```

Otherwise, is there a way to get all posts for the day?

Thanks,
Jeremy

**Comment by RStankov** [comment]
@jeremyrajan Pusher integration isn't official, it is made by community members. I don't know if it working 😅 

Ping them for issues. 

https://github.com/pusher-community/pusher-realtime-producthunt

**Comment by RStankov** [comment]
You can use [posts](http://api-v2-docs.producthunt.com.s3-website-us-east-1.amazonaws.com/operation/query/#posts) field and paginate it, because we feature more than page limit posts per day.

**Comment by jeremyrajan** [comment]
ok perfect! thank you :)

Could you please increase my rate limit, if that's ok? :)

It's under jeremyrajan@gmail.com

Thank you!

**Comment by RStankov** [comment]
@jeremyrajan how much increase do you need?

**Comment by jeremyrajan** [comment]
can I know whats the current rate limit? I only get 429 if I do few calls in a min.. maybe 20-30% increase would be nice? :)
