### ISSUE TITLE
Webhook Required

### ISSUE THREAD

**Issue by Pabbly** [producthunt/producthunt-api#229]
Hello Team,

Hope you guys are doing well!

Paras here from the Pabbly team, and I am here to present an integration solution for your product users.

Pabbly Connect is a new silo for making integration automation between 2 or more apps. A new and strong Zapier alternative that holds more than 600+ integration - https://www.pabbly.com/connect/

Lately, we have been getting a lot of users who are willing to see your Product hunt enlisted in the Pabbly Connect list. Thus to complete the integration we require the Webhook Documentation.

If you guys can provide us with the Webhook documentation of yours for the following endpoints, we can easily get the trigger and action event available for integration.

We would look forward to your response regarding the same.

Paras

**Comment by RStankov** [comment]
He, at the moment we don't have plans to provide webhook integrations.
