### ISSUE TITLE
API rate limits increase

### ISSUE THREAD

**Issue by Sannedak** [producthunt/producthunt-api#230]
Hello! I am one of the organizers of a [Students Labs](https://studentlabs.ru/). My team is doing a Product Hunt android app. And we need to increase the limit of requests by 7 times. This will help for our testers. Thanks a lot!

**Comment by RStankov** [comment]
@Sannedak  can only increase 5 for now. What is your PH account username?

**Comment by Sannedak** [comment]
@RStankov 
Account name: maxim_turchin
Thanks!

**Comment by RStankov** [comment]
@Sannedak  Done
