### ISSUE TITLE
API Rate Limit Increase

### ISSUE THREAD

**Issue by hellokfk** [producthunt/producthunt-api#232]
Hey,
I want to analyze some 2021 data of ProductHunt. I have some questions like which is the most popular day to launch a product etc. After that, I want to make a product with these results and launch it on Product Hunt. Do you have a chance to increase the rate limits?

Application ID: 54828

In addition, 

1- Can we access the product's badge information and free options information via API?
2- Product Hunt API V1 appears to be deprecated. But it is still usable. When will it be completely closed?
3- How can we access the creation time of users' votes via v2 API? Like this: https://api.producthunt.com/v1/docs/voting_for_posts/votes_index_see_all_votes_for_a_user
4- How can we access the viewer's email address via v2 API like "v1/me"

**Comment by RStankov** [comment]
1. Not currently
2. We don't have exact date yet.
3. We don't provide this information in v2 
4. We don't allow this
