### ISSUE TITLE
API Usage

### ISSUE THREAD

**Issue by psikomanjak** [producthunt/producthunt-api#233]
Hello PH,

I am the developer behind ([launchtorch.io](url)). 

We are building a free tool for people to search where a product is launched and how it performed. 

Regarding that the tool is as per the requirements FREE, the API limits only into a few searches, and I wanted to ask if it would be available to increase?

Thanks

**Comment by psikomanjak** [comment]
@RStankov any update on this?

**Comment by RStankov** [comment]
What is the product hunt account used to register the app?

**Comment by psikomanjak** [comment]
It's https://www.producthunt.com/@big_ben

**Comment by RStankov** [comment]
Increased your limits.
