### ISSUE TITLE
API authorization & private+write access

### ISSUE THREAD

**Issue by Sannedak** [producthunt/producthunt-api#234]
Hello! My team want implement authorization in android app, but face with limitations. 
1) API force us to use WebView to get access grant, but official app doesn't use this.
2) In web site (inside WebView) there's no Google and Apple Sign In only Twitter, Facebook and AngelList.
Q: How to properly implement Sign In?

And additionally we want private+write access.

PH account username: maxim_turchin

Thanks!

**Comment by RStankov** [comment]
Hey, currently we don't provide those to 3rd party apps due to security reasons.
