### ISSUE TITLE
"Query has complexity of 1126, which exceeds max complexity of 1000". API Rate Limit

### ISSUE THREAD

**Issue by huuphongnguyen** [producthunt/producthunt-api#236]
Hello Product Hunt API team, 

I'm developing my personal site: https://phong.vn and working on a section which is including my Product Hunt Upvoted List. I think the limit of API is bigger but supprised that I reached it while developing.

I'm using Next.js and Apollo to fetching Graphql through getStaticProps function. (getStaticProps is refreshing every single save on local, so that why I reached Rate Limit too fast.)

Could I expand the Rate Limit for this thing? It's for personal site, not for commercial.

Here is my PH profile: https://www.producthunt.com/@isnhp

Thank you so much for supporting.

**Comment by RStankov** [comment]
What is the query you are running? 

The complexity is not API rate limit but how much data can a single query have.

**Comment by huuphongnguyen** [comment]
> What is the query you are running? 
> 
> 
> 
> The complexity is not API rate limit but how much data can a single query have.

Here is query I am using

query phongPHVoted {
    user(username: "isnhp") {
      votedPosts(first: 10) {
        edges {
          node {
            name
            tagline
            thumbnail {
              url
            }
            votesCount
            isVoted
            slug
            commentsCount
            topics(first: 2) {
              edges {
                node {
                  name
                }
              }
            }
          }
        }
      }
    }
  }

**Comment by huuphongnguyen** [comment]
You can see it in my open-source website: https://github.com/huuphongnguyen/phong.vn/blob/main/graphql/ProductHuntQuery.js

**Comment by huuphongnguyen** [comment]
I just remove some part of my query and it's working. I think I have many element in query. I have remove some part of my query before but the complexity was not changed, so I think it from rate limits 😅. 
Thank you so much for pointing it out. 
Could I ask more information about rate limit? 
How many request to reach the limits? 
Could you increase a little bit for me just in case I won't need to make request in the future? 
Really really appreicate it.

**Comment by huuphongnguyen** [comment]
Anyone please check my case. 👋

**Comment by RStankov** [comment]
We can't increase complexity per user and we don't want to increase complexity for everyone at this stage.
