### ISSUE TITLE
Login view improvements proposal

### ISSUE THREAD

**Issue by markkurcz** [producthunt/producthunt-api#237]
Hi there,

I recently started connecting my app with the Oauth2 flow to the PH API v2 and noticed, that the login view looks a bit odd on iOS devices (see attached image from iPhone 12 - iOS14), so I gathered a few ideas to improve the UI on mobile devices during the login.

- on mobile devices it would be awesome if the buttons (twitter, facebook, angelist) would be displayed in a column following each other (css - flow-direction: column)
- the buttons themselves would look nicer if the default form style would be removed (css - -webkit-appearance: none)
- it would be the cherry on the top if the buttons would have the official icons like on the main PH login popup

![IMG_3223](https://user-images.githubusercontent.com/16936941/130492991-b9e2117f-d5ca-44d2-95dc-23e02cf415cb.jpg)

**Comment by RStankov** [comment]
Thanks for reporting will take a look.

**Comment by RStankov** [comment]
This is resolved now.
