### ISSUE TITLE
Commercial API Usage

### ISSUE THREAD

**Issue by hellokfk** [producthunt/producthunt-api#244]
I want to develop a commercial product that uses the Product Hunt API.

This product will provide a launch report and competitor analysis.
You can get more information from here:
https://launchkitty.com/

In what situations can you allow me to use the API? I have listed the commercial usage options below. Can you answer the items as appropriate or not appropriate one by one? I will choose one of the appropriate items as the commercial model.

- [ ] All features of the product should be paid.
- [ ] This product should offer a free trial.
- [ ] This product should include a free package.
- [ ] First use of the product should be free, subsequent uses should be paid.
- [ ] Other (Please, let me know other appropriate options for you)

Thanks.

**Comment by hellokfk** [comment]
Hey @RStankov, any update on this?

**Comment by RStankov** [comment]
@hellokfk  Checked with our team. Our API shouldn't be used for commercial purposes and we don't have plan to allow it for commercial use at this point.

**Comment by hellokfk** [comment]
@RStankov Thanks for your answer. I saw upvotebell.com while making the competition research. Did this product get your commercial approval?

**Comment by RStankov** [comment]
It didn't. Site is 404, can you give me their URL.

**Comment by hellokfk** [comment]
Sorry, the correct url is https://upvote-bell.com/

They have pricing plan: https://upvote-bell.com/pricing

Also they launched 2 times on PH.  So I thought they have commercial approval from you.
https://www.producthunt.com/posts/upvote-bell-2-0
https://www.producthunt.com/posts/upvote-bell

**Comment by RStankov** [comment]
No they haven't. Will look into them.

**Comment by niksib** [comment]
Hello, I am a maker of Upvote Bell, before adding paid plan I contacted with hello@producthunt.com and they approve that I can add paid plans.

**Comment by hellokfk** [comment]
Thanks for your information @niksib. 
As far as I understood from what @niksib has said that my product might be approved by you, too. Also, Upvote Bell is still alive although you know it's a paid product using Product Hunt API. So, I can launch my product, too, right? If there is a difference between my product and Upvote Bell, can you inform me about that? @RStankov
