### ISSUE TITLE
Users email not available in v2 schema

### ISSUE THREAD

**Issue by thinkverse** [producthunt/producthunt-api#247]
Hi there, this isn't an issue per-say and more of a question and suggestion. I tried to look up if there was a reason as to why the email isn't available when accessing the users' information using the v2 API.

The email was included in v1 under the `/me` endpoint but is not available anymore in v2.

Cannot find any reason for this, any chance we could add `email` to the `User` schema? 🤔

**Comment by RStankov** [comment]
Yes, we don't provide user email in v2 intentionally and will be deprecating its use in v2
