### ISSUE TITLE
API Rate Limit

### ISSUE THREAD

**Issue by michaelcarrano** [producthunt/producthunt-api#248]
Hi,

I am wondering if I can get API rate limit increased on my account. My Product Hunt username is the same as Github - michaelcarrano

It does not seem possible but want to double check, is there a way to get the website directly without having to go through the redirect url?

```
query {
  posts(first: 10, order: NEWEST) {
    edges {
      node {
        name
        createdAt
        website // This is a producthunt.com link that redirects to the real website submitted.
        url
      }
    }
  }
}
```

Thank you

**Comment by michaelcarrano** [comment]
@RStankov are you able to help with this request? Thank you.

**Comment by RStankov** [comment]
We don't allow direct website access.
