### ISSUE TITLE
V2- Query returning partial response

### ISSUE THREAD

**Issue by appgraze** [producthunt/producthunt-api#250]
Hey PH Team!

I'm using your V2 API to query data for comments on posts. Currently, this is all happening on a No-Code platform Bubble.io, the response is coming in just fine. The issue is my totalCount for comments is displaying 81 but I only receive 20 in my response. I'm not well-versed in graphql and I knew just enough to put this query together. I'm not exactly sure if pagination is the issue here. I'm checking pageInfo for nextPage and so on but all returning false. If you could help in any way I would greatly appreciate it!

Thank you,

Aram

GraphQl Query

query GetPost($id: ID!) {
post(id: $id) {
comments {
totalCount
edges {
node {
body
createdAt
url
user {
name
headline
profileImage
}

}
cursor
}
pageInfo{
endCursor
hasNextPage
hasPreviousPage
}
}
}
}

Variables

{
"id": "popwork"
}

**Comment by RStankov** [comment]
Hey,

This is expected behaviour. We paginate the results in `comments` field. Max comments per page is 20. You do pagination by providing: `after` cursor, `first` as limit:

```graphql
query GetPost($id: ID!, $cursor: String) {
  post(id: $id) {
    comments(first: 20, after: $cursor) {
      totalCount
      edges {
        node {
          body
          createdAt
          url
          user {
            name
            headline
            profileImage
          }
        }
      }
      pageInfo{
        endCursor
        hasNextPage //- this is cursor for next page
        hasPreviousPage
      }
    }
  }
}
```

**Comment by appgraze** [comment]
Thank you for your response. I'm trying to pull all comments in one call.
Do I have to make multiple requests if hasNextPage is true? Is there a way
to receive all comments in one request? I'm not sure how to save the
endCursor value to feed it back as a variable... Sorry, I don't have much
GraphQL experience and your rest api is deprecated...

**Comment by RStankov** [comment]
No worries. We don't allow all comments by single query, because this will make it too heavy of a load.

You get `endCursor` and pass it for a second query.
