### ISSUE TITLE
nextpage not working the way it used to

### ISSUE THREAD

**Issue by Scotty8942** [producthunt/producthunt-api#251]
The URL of a problematic page: https://images.socialcentral.net/MorePics/images/110265293037386/662209

Describe what's wrong on that page: I used to be able to use the nextpage app without the file type (.gif, .jpg, etc) at the end and it would show any file type. Now I need to add the specific file type at the end to show the correct page result. Has something changed? How do I get it to work the way it used to without adding the file type at the end?

Tell me your browser version, OS version and nextpage addon version: Firefox 96.0.1 and nextpage 1.0

**Comment by RStankov** [comment]
This is not related to Product Hunt public API.
