### ISSUE TITLE
Missing 'developer_token' for scripts?

### ISSUE THREAD

**Issue by iwootten** [producthunt/producthunt-api#253]
The v2 ProductHunt API docs state:

"The oauth2 flow is a bit of a overkill if you just want to run a few scripts
We provide a developer_token (does not expire, linked to your account) in the app dashboard"

Taking a look, there doesn't appear to be any such token in the dashboard, just the ability to add an app. 

Has it been removed?

![Screenshot 2022-01-27 at 17 37 27](https://user-images.githubusercontent.com/3598161/151413215-9dc18835-cfa6-4527-972e-691b0327aebe.png)

**Comment by RStankov** [comment]
It is still there. When you create an application via "Add An Application" and then you can get the developer token.
