### ISSUE TITLE
Heavy requests (3000+ requests)

### ISSUE THREAD

**Issue by hugohamelcom** [producthunt/producthunt-api#256]
I am having 2 errors when making requests to the Product Hunt API.
- Request Timed Out
- Oops, something went wrong - your request was not processed correctly.

I am not sure where is the error coming from. 
Is it because I am making too many requests at the same time?
Is the error from Apipheny or Product Hunt API?

**Comment by RStankov** [comment]
Can you check again? You might be hitting rate limits

**Comment by hugohamelcom** [comment]
Just did a test, and was doign about 5 requests per hour, and it is still showing me sometimes: Request Timed Out

**Comment by RStankov** [comment]
Here is the information on rate limits:

https://api.producthunt.com/v2/docs/rate_limits/headers


Last week we have issues with our database and that might have caused the timeouts.

What queries are you running?

**Comment by hugohamelcom** [comment]
Thank you :) The request I use is with the V1: https://api.producthunt.com/v1/posts?day=2022-02-21

**Comment by RStankov** [comment]
V1 is deprecated. This might be the reason why you get timeouts.
