### ISSUE TITLE
API Rate Limit Request

### ISSUE THREAD

**Issue by simonblackman** [producthunt/producthunt-api#258]
Hi,

I am working on a research project together with a colleague of mine that requires us to make a larger amount of requests over a short period of time. As a result of this, I am using the V1 API to be able to request more per call before hitting my limits and sleeping.

Would it be possible to temporarily increase the rate limit of my account to allow me to capture the data necessary in a slightly shorter time? I will happily share the project and my findings once finalized.

Best,
Simon

**Comment by RStankov** [comment]
V1 is deprecated and we don't change rate limits there. Consider using v2
