### ISSUE TITLE
API Rate Limit Request

### ISSUE THREAD

**Issue by pbardea** [producthunt/producthunt-api#269]
Hi there!

I'm building an app using the Product Hunt API and am sometimes running into rate limit issues when testing. I'm hoping to post it soon to ProductHunt, could I get my rate limit bumped for a bit? Username: @paul_bardea, App Name: Explorer.

Thank you!

**Comment by pbardea** [comment]
Just wanted to mention that I'm caching requests, but still hitting rate limits when fetching votes for a product with the GraphQL API since the page size is relatively small (20)

**Comment by RStankov** [comment]
Hey, I doubled your API limits
