### ISSUE TITLE
Fair use question

### ISSUE THREAD

**Issue by edanweis** [producthunt/producthunt-api#271]
I would like to analyse the pricing pages of a large number of products on product hunt, for research purposes, and writing an article about it.

Can I have permission to crawl, or receive a data dump containing only the string of a post's website URL, for products listed on PH?

If that's considered fair use, a simple one column csv may be less load on the server than hitting the graphql endpoint. Thanks

**Comment by RStankov** [comment]
Hey, we are not exposing this data publicly as API access by design. You shouldn't use this data via private API use.
