### ISSUE TITLE
v2 API to Query Comments

### ISSUE THREAD

**Issue by imomin** [producthunt/producthunt-api#273]
I was wondering if there is a way to Query.Comments to get latest comments (sortBy createdAt) with "after" createdAt or cursor filter. A v2 api replacement for [comments_index_sort_by_created_at.](https://api.producthunt.com/v1/docs/comments_and_comment_threads/comments_index_sort_by_created_at).
I would like to query something similar to following.

      comments(order: NEWEST, after:"$cursor") {
        edges {
          node {
            id
            body
            createdAt
            url
            parentId
            user {
              id
              name
            }
            post {
              id
              url
              topics {
                nodes {
                  name
                }
              }
            }
          }
        }
      }

**Comment by RStankov** [comment]
Currently we don't support this.
