### ISSUE TITLE
Bad Request for Coda.io Packs

### ISSUE THREAD

**Issue by faridsabitov** [producthunt/producthunt-api#275]
Hi Team, 
When I send a request via Coda.io Pack, I receive this message
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/18511447/203849818-d2bf0e12-58a5-4b5b-8d75-273f13325976.png">

But I'm sending it properly
<img width="540" alt="image" src="https://user-images.githubusercontent.com/18511447/203850067-072d98ec-962c-443c-8615-c17301413079.png">

Here is my code:
```
 execute: async function ([], context) {
    const requestBody = JSON.stringify({
      query: `{
        user(id: "576576")) {
          followers {
            edges {
              node {
                id
              }
            }
          }
        }
      }`
    });
    let response = await context.fetcher.fetch({
      method: "POST",
      url: "https://api.producthunt.com/v2/api/graphql",
      body: requestBody,
    });
    let data = response.body;
    return data;
  },
});
```

Thank you a ton! I've spend 30 mins trying to figure it out

**Comment by RStankov** [comment]
I'm not aware `Coda.io Pack`. Can you send me the CURL of this.

**Comment by faridsabitov** [comment]
Hi @RStankov, unfortunately, there is no way for me to export CURL out of coda but here is the full request details

Object
request:Object
method:"POST"
cacheTtlSecs:300
headers:Object
Authorization:"Bearer <<<REDACTED by Coda>>>"
body:Object
query:"{
        user(id: \"576576\") {
          followers {
            edges {
              node {
                id
              }
            }
          }
        }
      }"
url:["https://api.producthunt.com/v2/api/graphql"](https://api.producthunt.com/v2/api/graphql)
response:Object
status:400
headers:Object
alt-svc:"<<<REDACTED by Coda>>>"
cache-control:"<<<REDACTED by Coda>>>"
cf-cache-status:"<<<REDACTED by Coda>>>"
cf-ray:"<<<REDACTED by Coda>>>"
connection:"<<<REDACTED by Coda>>>"
content-type:"application/json; charset=utf-8"
date:"Fri, 25 Nov 2022 15:46:24 GMT"
referrer-policy:"<<<REDACTED by Coda>>>"
server:"<<<REDACTED by Coda>>>"
strict-transport-security:"<<<REDACTED by Coda>>>"
transfer-encoding:"<<<REDACTED by Coda>>>"
vary:"Origin, Accept-Encoding"
x-content-type-options:"<<<REDACTED by Coda>>>"
x-download-options:"<<<REDACTED by Coda>>>"
x-frame-options:"<<<REDACTED by Coda>>>"
x-permitted-cross-domain-policies:"<<<REDACTED by Coda>>>"
x-request-id:"<<<REDACTED by Coda>>>"
x-runtime:"<<<REDACTED by Coda>>>"
x-xss-protection:"<<<REDACTED by Coda>>>"
body:Object
data:null
errors:Array[1]
0:Object
error:"query_missing"
error_description:"The query object is missing in the request body."

**Comment by faridsabitov** [comment]
I found the issue. I needed to specify the headers as json format. Closing the issue, thank you!
