### ISSUE TITLE
Collection Posts are mixed up with Collection Products?

### ISSUE THREAD

**Issue by faridsabitov** [producthunt/producthunt-api#276]
Hi Team,

Thank you for your amazing work! I have a question about collections and posts. Looks like there is an issue; when I'm pulling collection posts, I'm pulling collection products, and the numbers are mixed up, here is the full explanation

https://share.descript.com/view/AgKXt3pwqEm

**Comment by faridsabitov** [comment]
@RStankov, please let me know if you need more data from my side, thank you!

**Comment by RStankov** [comment]
Hey, the issue is on the web we migrated collections to use our new Product model (which powers [Product Hubs](https://www.producthunt.com/products/slack)). We still haven't exposed Product models in the API.
