### ISSUE TITLE
Incorrect order for posts with order: RANKING

### ISSUE THREAD

**Issue by danmindru** [producthunt/producthunt-api#277]
Hey @RStankov, for the following gql

```gql
query posts(
  $postedBefore: DateTime
  $postedAfter: DateTime
  $first: Int
  $after: String
  $last: Int
  $before: String
  $order: PostsOrder
) {
  rows: posts(
    postedAfter: $postedAfter
    postedBefore: $postedBefore
    first: $first
    after: $after
    last: $last
    before: $before
    order: $order
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      name
      votesCount
    }
  }
}
```

With variables set to:

```json
{
  "order": "RANKING",
  "postedBefore": "2023-01-28T00:00:00.000Z",
  "postedAfter": "2023-01-27T00:00:00.000Z",
  "first": 5
}
```

The results differ from the Product Hunt time travel page.
Notice the order of 'WorkHub Connect for Mobile'

It should be `#1` but is ranking `#2` by the gql query.

API response is:

```json
{
  "data": {
    "rows": {
      "totalCount": 5,
      "pageInfo": {
        "hasNextPage": true,
        "endCursor": "NQ"
      },
      "nodes": [
        {
          "name": "Internet Is Beautiful",
          "votesCount": 729
        },
        {
          "name": "WorkHub Connect for Mobile",
          "votesCount": 663
        },
        {
          "name": "Inside AI",
          "votesCount": 521
        },
        {
          "name": "The Help Center Academy",
          "votesCount": 335
        },
        {
          "name": "Makelog",
          "votesCount": 284
        }
      ]
    }
  }
}
```

<img width="2306" alt="Screenshot 2023-02-01 at 18 58 16" src="https://user-images.githubusercontent.com/1515742/216125639-6b540337-4e1b-41db-b83e-3e03d0862e0e.png">

Will you please take a look?
Thanks so much,
Dan

**Comment by RStankov** [comment]
Yes, this works as intended.

Time-travel is freezing ranking for a day, week, month. We exclude voting activity after this period.

While this query has arbitrary range of dates and ranks posts with total posts in whole post history.

**Comment by danmindru** [comment]
@RStankov thanks for looking into this.
Any plans to introduce a new post order type e.g. `order: TIME_TRAVEL_RANKING` that would give the same results as time travel does? That would be quite useful to me, if possible.

All the best & have a nice weekend!

**Comment by RStankov** [comment]
We don't have any immediate plans to do so. Especially, since we plan to do a backend restructuring in the next couple of months.

**Comment by danmindru** [comment]
Alright :(
It would be very cool to be able to get this data.
Or alternatively, be able to get dailyRank & weeklyRank for a post.

Hope you keep this in mind :)
