### ISSUE TITLE
Add order or allow filtering posts by featuredAt date: Cannot get actual ranking order of posts

### ISSUE THREAD

**Issue by danmindru** [producthunt/producthunt-api#278]
Hey, 

Do you have any plans to return order for the day (ideally: week & month too) when querying posts?

Because posts can have a different `createdAt` & `featuredAt` date, ordering by ranking is meaningless:

<img width="1071" alt="Screenshot 2023-02-20 at 15 30 02" src="https://user-images.githubusercontent.com/1515742/220134633-3603ad9a-1838-4c65-b66a-80383cdf0ea6.png">

In this screenshot we have a post from `2016-12-05` ranked against a post `2016-12-02` etc.

Alternatively, could the posts query allow filtering by `featuredAt` instead of `createdAt`? That could get the job done without changing the model.

So something in the lines of:

```
posts (PostConnection!) 
    Look up Posts by various parameters. 

Argument	Type	    Description 
...
order	        PostsOrder  Define order for the Posts. The default value is RANKING. 
featuredAfter	DateTime    Select Posts which were featured after the given date and time. 
featuredBefore	DateTime    Select Posts which were featured before the given date and time.
...
```

This would be *so amazing* if possible. Hope you'll consider adding it and thanks for listening out!

**Comment by RStankov** [comment]
@danmindru Thanks for the suggesting. We will put it into consideration and see if we should add this.

**Comment by danmindru** [comment]
@RStankov thanks for considering :) 
Cheers,
Dan
