### ISSUE TITLE
API bug with Makers data

### ISSUE THREAD

**Issue by boris-borisov** [producthunt/producthunt-api#279]
I've been experimenting with the Product Hunt API for Posts:

https://api.producthunt.com/v1/posts?days_ago=1

However, it stopped working recently - it doesn't return the Makers anymore :-(

It returns the other values, but not the Makers values (only "Redacted" for all).

I think it's a bug - could you fix it?

**Comment by RStankov** [comment]
@boris-borisov API v1 has been deprecated for couple of years now. We will be shutting it down later this year.

**Comment by boris-borisov** [comment]
@RStankov Okay, thank you for the reply, Radoslav! 👍

I will look into the v2 API if it can support the equivalent functionality:
https://api.producthunt.com/v1/posts?days_ago=1

If you know from the top of your mind, you can let me know, it will save us some research time 👍

**Comment by boris-borisov** [comment]
@RStankov 

The API v2 - also has the problem that it does NOT return the Makers of a product :-(

Instead of getting the list of Makers for a given product, I'm getting "Redacted" for all of them.

Do you know if this is a bug or the intended behavior?
