### ISSUE TITLE
OAuth2 with token expiration should implement token refresh

### ISSUE THREAD

**Issue by grayj** [producthunt/producthunt-api#28]
User tokens currently expire after 60 days, but there is no API endpoint for sending an OAuth2 token refresh request.

Workarounds:

(1) Remind users to re-authenticate every < 60 days to avoid breaking any API integrations. If users fail to re-authenticate in time (every 60 days), any features of a 3rd party service which connect to the PH API will stop working. Not good.

(2) Use app-level auth if at all possible, in lieu of making user-level requests. This currently works for most things other than the "me" endpoint, since there is no rate limiting or write access in place. However, it may not remain practical as the API continues to grow, and it's possible that I'm overlooking other endpoints which need user context.

**Comment by mjmsmith** [comment]
+1

**Comment by neupaneshapath** [comment]
+1

**Comment by sahilsarpal** [comment]
+1

**Comment by sahilsarpal** [comment]
when are you providing refresh access token ?

**Comment by TheShapGuy** [comment]
This would be my suggestion,

Since the expiry is always decreasing, is it possible to add to the expiry if the user is continually authenticated however if the user is not using the app, the expiry will always be decreasing and when it reaches 0, the user will have to re-authenticate to use PH through token access. 

Possible? Any thoughts?

**Comment by TheShapGuy** [comment]
http://goo.gl/4pExt8

**Comment by bobby-brennan** [comment]
+1, many of my users are hitting the 60 day mark now :/

**Comment by dkogias** [comment]
+1 yes please

**Comment by OpakAlex** [comment]
Guys, any progress? If your token is expired, you MUST implement refresh endpoint.

**Comment by andreasklinger** [comment]
responding here for future google searchers: 
tokens are now infinite - no refresh needed

**Comment by OpakAlex** [comment]
@andreasklinger cool. It was hard did 4 month ago?  Change one config in line and deploy...Thanks a lot! Great Job!
