### ISSUE TITLE
API issue with user object

### ISSUE THREAD

**Issue by gouterz** [producthunt/producthunt-api#280]
Currently I'm using Product API V2 with the endpoint: https://api.producthunt.com/v2/api/graphql to fetch comments but the user object returns "[REDACTED]" for name, username and other values

Could you let me know why this is happening?

**Comment by denisj** [comment]
Same here.

**Comment by RStankov** [comment]
This is the intended behaviour. We are redacting certain user information from the API.

**Comment by ztat** [comment]
@RStankov What feedback led to this decision? This is clearly a recent change with no log of the information.
