### ISSUE TITLE
Unexpected posts returned by query

### ISSUE THREAD

**Issue by danmindru** [producthunt/producthunt-api#282]
Hi, for the following query:

```gql
query posts(
  $postedBefore: DateTime
  $postedAfter: DateTime
  $url: String
  $first: Int
  $after: String
  $last: Int
  $before: String
  $order: PostsOrder
) {
  rows: posts(
    postedAfter: $postedAfter
    postedBefore: $postedBefore
    url: $url
    first: $first
    after: $after
    last: $last
    before: $before
    order: $order
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      name
       createdAt
       featuredAt
      votesCount
    }
  }
}
```

filtered by:

```json
{
	"order": "RANKING",
	"postedBefore": "2023-03-04T23:59:59.000Z",
	"postedAfter": "2023-03-04T00:00:00.000Z",
	"first": 20
}
```

The first 2 results have 
a) Incorrect rank
b) Should not be returned for this date range

<img width="1221" alt="Screenshot 2023-03-05 at 15 34 16" src="https://user-images.githubusercontent.com/1515742/222966882-60b92958-2279-427b-9533-a20e56d74eca.png">

Results: 
```json
{
  "name": "AutoSlide",
  "createdAt": "2023-03-04T21:03:04Z",
  "featuredAt": "2023-03-05T08:24:00Z",
  "votesCount": 16
},
{
  "name": "ToDues",
  "createdAt": "2023-03-04T18:41:53Z",
  "featuredAt": "2023-03-05T08:28:00Z",
  "votesCount": 11
},
```

I would expect that these posts are returned on 03-05, not 03-04.
This makes the `RANKING` order useless - related to #278. 

Cheers,
Dan

**Comment by jacobcrump** [comment]
Hey Dan,

Thanks for reaching out about this. It looks like the first 2 are being returned due to their `createdAt` date. I'll discuss this with the team and see if we want to introduce new options here in the future. Appreciate you highlighting this!

Best,
Jake
