### ISSUE TITLE
Coming Soon via API?

### ISSUE THREAD

**Issue by nikspr** [producthunt/producthunt-api#283]
Heyo, is it possible to pull the information about "[coming soon](https://www.producthunt.com/coming-soon)" products via the API?

Best
Niklas

**Comment by jacobcrump** [comment]
Hi Niklas,

Thanks for reaching out! We don't have any plans to include this at the moment. I'll be sure to pass along the suggestion to the rest of the team, though, as a potential option in the future.

Best,
Jake
