### ISSUE TITLE
Redacted Field in GQL Response 

### ISSUE THREAD

**Issue by ztat** [producthunt/producthunt-api#286]
Seeing field that was previously reported with no issues showing up as redacted now in the API 

                        "user": {
                            "id": "0",
                            "name": "[REDACTED]"
                        },

Please advise

**Comment by AndrewRadev** [comment]
We've changed the API to redact other users' data for privacy reasons. Here's the relevant documentation: http://api-v2-docs.producthunt.com.s3-website-us-east-1.amazonaws.com/object/user/. If you have a user token, you should still be able to fetch your own data.

**Comment by ztat** [comment]
@AndrewRadev Would be nice to add a change log to the documentation

**Comment by ztat** [comment]
Also seems a stretch to say that this is for privacy reasons... What feedback led to this decision?

**Comment by alanhamlett** [comment]
@AndrewRadev I implemented the OAuth flow with a user token but even for the currently authenticated user I'm always getting zero followers totalCount. Here's the query:

`{ viewer { user { id username profileImage followers { totalCount } } } }`

And the incorrect response:

```json
{
  "data": {
    "viewer": {
      "user": {
        "id": "6843",
        "username": "wakatime",
        "profileImage": "https://ph-avatars.imgix.net/6843/7ea9538e-228d-42c8-a338-8ec73eca155b?auto=format&fit=crop&crop=faces&w=original&h=original",
        "followers": {
          "totalCount": 0
        }
      }
    }
  }
}
```

Can you help fix this bug so it works for the currently authenticated user? I understand wanting to restrict access for other users, but according to your comment it should work for the current user.
