### ISSUE TITLE
Low Number of Query Responses

### ISSUE THREAD

**Issue by MaxwellCDavis** [producthunt/producthunt-api#289]
Hi there,

I put together this query and for every response I'm only getting 20 products coming back.  Am I missing something to get more than 20 responses?  TIA!

query Posts {
    posts(postedAfter: "2023-03-25T07:01:00Z", first: 100) {
        totalCount
        nodes {
            commentsCount
            createdAt
            description
            featuredAt
            id
            isCollected
            isVoted
            name
            reviewsCount
            reviewsRating
            slug
            tagline
            url
            userId
            votesCount
            website
        }
    }
}

**Comment by TysBradford** [comment]
@MaxwellCDavis I have the same issue. Did you resolve it?

**Comment by KC-Zhang** [comment]
same issue here
