### ISSUE TITLE
api v2 return 403 error with same origin

### ISSUE THREAD

**Issue by leesanQAQ** [producthunt/producthunt-api#300]
my request is:
![image](https://github.com/producthunt/producthunt-api/assets/18282182/d87a381a-eae5-44ba-9fb4-056233b61608)

response is:
![image](https://github.com/producthunt/producthunt-api/assets/18282182/de9b8711-bb39-4851-97b8-feb03fb08b04)

pls take a look, thanks

**Comment by leesanQAQ** [comment]
found some similar issues here
#290 
#266

**Comment by WgCg** [comment]
I encountered the same problem. May I ask how you solved it? @leesanQAQ
