### ISSUE TITLE
404 not found on posts#show when querying for an existing product

### ISSUE THREAD

**Issue by mikejarema** [producthunt/producthunt-api#36]
Specifically: http://www.producthunt.com/posts/tailor

It looks like it has an ID of 7783 (see http://www.producthunt.com/posts/7783).

However:

```
$ curl -H "Authorization: Bearer MYTOKEN" "https://api.producthunt.com/v1/posts/7783"
{"error":"not_found","error_description":"We could not find any object with this ID"}
```

Also, this particular hunt doesn't show up in search on the site proper either. [Search "tailor"](https://www.producthunt.com/#!/s/Tailor), not there.

**Comment by jjhageman** [comment]
Hey @mscoutermarsh I believe post ids are 8337 and 9950 are having the same issue.
