### ISSUE TITLE
Lookup User by Twitter Handle

### ISSUE THREAD

**Issue by davecom** [producthunt/producthunt-api#37]
I was communicating with PH staff by email and they told me it would be better to open an issue. As far as I can tell there is no facility to search through the PH user directory for a specific user by Twitter handle. That would be a great endpoint to have (or please show me how it can currently be done). Thanks.

**Comment by mscoutermarsh** [comment]
Hey!

username on PH is identical to the users twitter handle.

Request:
`GET v1/users/twitter_handle_here`

Will give you all info about the user if they are signed up for PH. 

more info here:
https://api.producthunt.com/v1/docs/users/users_show_get_details_of_a_user
