### ISSUE TITLE
Votes endpoint independent of posts and users

### ISSUE THREAD

**Issue by jjhageman** [producthunt/producthunt-api#38]
Any plans to add `/v1/votes/all` as an endpoint?

**Comment by mscoutermarsh** [comment]
Hey, not currently. What kind of use case are you thinking?

**Comment by jjhageman** [comment]
Hey, I just emailed @andreasklinger with more details on the exact use case. Basically, I am building a recommendation engine that is driven off a user's past votes. So I'm looking for the easiest way to stay up to date, at least on a daily basis, with the votes data.

**Comment by andreasklinger** [comment]
for future readers: for the initial seeding we provide csv files (easier than scraping all of our site)
