### ISSUE TITLE
Cannot retrieve /posts/votes in Collection

### ISSUE THREAD

**Issue by gillesbertaux** [producthunt/producthunt-api#40]
`https://api.producthunt.com/v1/posts/{{post-id}}/votes` works w/ posts on the homepage. But it won't work if the post is in a collection.

`https://api.producthunt.com/v1/posts/{{post-id-in-collection}}/votes` will give the following error:

````
{
error: "not_found",
error_description: "We could not find any object with this ID"
}
````

**Comment by andreasklinger** [comment]
Untouched for longer time - Archiving
