### ISSUE TITLE
Etags does not seem to work

### ISSUE THREAD

**Issue by yigit** [producthunt/producthunt-api#41]
Looks like etag handling does not work anymore.

Sample request and response:

    ---> HTTP GET https://api.producthunt.com/v1/posts?days_ago=1
    If-None-Match: W/"3f23cecff5bb56eecabfee81274aa33c"
    Accept: application/json
    Host: api.producthunt.com
    Authorization: Bearer <BEARER>
    Content-Type: application/json
    ---> END HTTP (no body)

    <--- HTTP 200 https://api.producthunt.com/v1/posts?days_ago=1 (1237ms)
    OkHttp-Selected-Protocol: spdy/3.1
    server: cloudflare-nginx
    date: Sat, 31 Jan 2015 19:49:00 GMT
    content-type: application/json; charset=utf-8
    set-cookie: __cfduid=db849ec3456da8968206ef0d7080e5e901422733739; expires=Sun, 31-Jan-16 19:48:59 GMT; path=/; domain=.producthunt.com; HttpOnly
    x-frame-options: SAMEORIGIN
    x-xss-protection: 1; mode=block
    x-content-type-options: nosniff
    x-rate-limit-limit: 900
    x-rate-limit-remaining: 886
    x-rate-limit-reset: 129
    etag: W/"3f23cecff5bb56eecabfee81274aa33c"
    cache-control: max-age=0, private, must-revalidate
    x-request-id: ccfaa07f-69cd-4fad-b0f6-b818be86433e
    x-runtime: 0.666834
    via: 1.1 vegur
    cf-ray: 1b186e0d8d5d0d9d-SJC
    OkHttp-Sent-Millis: 1422705976046
    OkHttp-Received-Millis: 1422705977008

I've tried stripping `W/` , did not help.

**Comment by mscoutermarsh** [comment]
Thanks! Looking into it & will get back to you.

**Comment by mscoutermarsh** [comment]
Hey, update on this. Etags are not working because our CDN is gzipping the json and changing the etag. Gzip = good :) so we don't want to disable it. Will update this issue when we have it working again. Not super high priority at the moment, so might be some time.

**Comment by andreasklinger** [comment]
to follow up on this - we are removing the CDN within this week and then gzip ourselves - ETags should work then as planned

**Comment by lfittl** [comment]
@yigit This is now resolved and API etags should work as expected.

Let us know if you run into any more issues, thanks for your patience!
