### ISSUE TITLE
Retrieving collections for post returning empty

### ISSUE THREAD

**Issue by arlin17** [producthunt/producthunt-api#42]
Testing the collection API for a project I'm building. 

API call: `https://api.producthunt.com/v1/posts/12799/collections`
Return (200):
```
{
  "collections" : []
}
```

See collection for Lift 2.0 here:
`http://www.producthunt.com/gregoiregilbert/collections/reach-your-goals`

**Comment by mscoutermarsh** [comment]
Confirmed this is a bug, sorry about that. will fix & update here when resolved.

**Comment by andreasklinger** [comment]
Untouched for longer time - Archiving
