### ISSUE TITLE
AJAX endpoint

### ISSUE THREAD

**Issue by peterlum** [producthunt/producthunt-api#43]
How do I go about getting a JSON object using your endpoints? I'm confused about retrieving data from product hunt's API for posts since it requires the token and a redirect URL. 

Currently I have the following:
  
var query_params = { client_id: '[my API Key]',
					response_type:'code',
					redirect_uri:'[my URI]',
					scope:'public+private',                 
                   };
$.ajax({
	url:'https://api.producthunt.com/v1/posts',
	type:'GET',
	data:query_params,
	crossDomain:true,
	dataType:'jsonp',
	success:function(data){
		console.log(data)
	},
	error:function(){
		console.log('Failed!');
	}
});

To make a simple 'GET' request, one needs to use the following route correct? 
https://api.producthunt.com/v1/oauth/authorize?client_id=[my API token]&redirect_uri=[my redirect URI]&response_type=code&scope=public+private

**Comment by mscoutermarsh** [comment]
hey! To access the `posts` endpoint, you only need to pass an `access_token` with the request.

The `client_id`, `client_secret` and `redirect_uri` are only used for retrieving an `access_token` (this is part of the oauth process). [More info here](https://api.producthunt.com/v1/docs/oauth_client_only_authentication/oauth_token_ask_for_client_level_token).

So, you'd complete the oauth process to get an `access_token`, and then use that token in all subsequent requests. Make sense? :smile:

If you're just playing around/testing things out. I recommend going to the [api dashboard](http://www.producthunt.com/v1/oauth/applications) and generating a developer only token. You can use this as the `access_token`.

btw. Remember to treat the token like a password & don't share it. The developer token is linked to your personal account & has access to your data.

Let me know if you have any more questions! :+1:

**Comment by peterlum** [comment]
Hi Mike,

Thanks for the help. I understand this process, it's just trying to figure
out a method in which to use a token on the client side without exposing it
as you've mentioned. Currently, I'm trying to do this strictly through
javascript and jquery. I've seen methods in which people have stored their
tokens in a separate php file and accessed that file to get the token when
making calls.

Basically my inquiry is, can I do all of this strictly with javascript and
AJAX on the client side without exposing the token? Like perhaps putting
the token into a JSON file of my own and using a call to that to acquire
the token? Thanks for any insight into this and for all of your help so far.


On Fri, Feb 13, 2015 at 6:22 PM, Mike Coutermarsh <notifications@github.com>
wrote:

> Closed #43 <https://github.com/producthunt/producthunt-api/issues/43>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/producthunt/producthunt-api/issues/43#event-235739472>
> .
>



-- 
Peter Lung Lum
BFACDT Parsons School of Design
Graphic Design & Illustration
www.peterlum.co

**Comment by mscoutermarsh** [comment]
You'd need to setup some intermediate proxy between your app and the API to keep the token safe.
