### ISSUE TITLE
Newer parameter in comments end point doesn't take into consideration child replies

### ISSUE THREAD

**Issue by bahaagalal** [producthunt/producthunt-api#46]
The bug happens, when you retrieve comments with the newer parameter, the response only includes the MAIN comments that happened after the newer parameter but doesn’t include any child comments even if it happened after the newer parameter.

**Comment by andreasklinger** [comment]
confirmed bug

to repeat in own words

```
user request latest comments
 - gets top level comments with nested comments 
user takes (any of those) ids to receive newer comments 
 - only receives new top level comments and their nested comments 
 - no new nested comments of "old" top level comments
```

**Comment by andreasklinger** [comment]
to tackle this: 

we added a new endpoint

you can now hit `/v1/comments` and also provide filters for post_id or user_id if needed
the comments responding are non-threaded

let me know if this is useful
https://api.producthunt.com/v1/docs/comments_and_comment_threads/comments_index_fetch_a_stream_of_all_recent_comments

**Comment by andreasklinger** [comment]
closing this for now - feel free to reopen
