### ISSUE TITLE
users/USER_ID/collections gives different result than users/USERNAME/collections

### ISSUE THREAD

**Issue by picsoung** [producthunt/producthunt-api#47]
Hi,

As I was playing with the API I found out that 
`users/USER_ID/collections` gives another result than `users/USERNAME/collections`

I assumed it will give me the same result as, `/users/USER_ID` and `/users/USERNAME` are doing the same thing.

Example:

`https://api.producthunt.com/v1/users/joerj/collections?`
gives 
```
{
    "collections": []
}
```

when `https://api.producthunt.com/v1/users/4845/collections`
```
{
    "collections": [
        {
            "id": 9282,
            "name": "Healthcare",
            "title": null,
            "created_at": "2015-02-18T07:27:38.648-08:00",
            "updated_at": "2015-02-18T07:27:38.681-08:00",
            "featured_at": null,
            "background_image_url": null,
...
}]}
```

Thanks

**Comment by andreasklinger** [comment]
Untouched for longer time - Archiving
