### ISSUE TITLE
Online API Docs are broken

### ISSUE THREAD

**Issue by brucek** [producthunt/producthunt-api#48]
From `https://api.producthunt.com/v1/docs` the right-hand sections do not open/link anywhere, so I can't see any API-specific docs.  JS console offers the following errors:

    https://assets.producthunt.com/assets/application-b608850744a6593d2fd10800317343b1.js
      Failed to load resource: the server responded with a status of 404 (Not Found)

    2443710756.js:28 Uncaught ReferenceError:
      jQuery is not defined

**Comment by andreasklinger** [comment]
Thanks - will fix today

**Comment by lfittl** [comment]
This is fixed now - sorry for the issue :)
