### ISSUE TITLE
Which scope to use for read-only access?

### ISSUE THREAD

**Issue by evanp** [producthunt/producthunt-api#49]
The docs for the API say for the scope parameter for OAuth authorization:

    scope (required) The scopes you want to have access to. For read/write use `public private`

I haven't requested read/write access and don't really need it. What should I use for 'scope'? 'public'? Blank? Something else?

**Comment by andreasklinger** [comment]
Ok that's not optimally explained

If you only require public information you can use `public`. 
If you need private information of the logged-in user go with `public private`. 
If you have write access and want to update user information you also need `public private`

Note that you need to be whitelisted to have write access

I will update the docs!

**Comment by andreasklinger** [comment]
closing for now - feel free to reopen
