### ISSUE TITLE
[Documentation Request] When does "today" start?

### ISSUE THREAD

**Issue by oelmekki** [producthunt/producthunt-api#52]
Hi,

I'm building an application that caches "today's" posts in database to 
perform computations on them. It is updated every hour.

I would love to take advantage of Etag to just download what's new 
every hours, and only flush the whole cache when day change, instead of 
flushing it all every hour.

Problem is : I have absolutely no idea what is "today" :) Does it start
at 0:00 GMT? SF time? On timezone from user requesting data (somehow)?

It would be nice to add this info in documentation for "`posts#index`:
Get the posts of today".

Thanks!

**Comment by mscoutermarsh** [comment]
Hey! We use SF time for today. A new day starts a `0:00 PDT -07:00`.

**Comment by oelmekki** [comment]
Noted, thanks for quick reply, @mscoutermarsh :)

I keep issue opened because you may want to add this in documentation
to avoid this question being asked further. Feel free to close it if
you prefer to.

**Comment by evanp** [comment]
Yeah, this is pretty valuable information.

**Comment by andreasklinger** [comment]
Closing - closed issues can be found via google
