### ISSUE TITLE
[Endpoint / Functionality Request] /resolve (allow lookup via URL)

### ISSUE THREAD

**Issue by sleinadsanoj** [producthunt/producthunt-api#55]
Mainly I'm thinking about posts, but this could also be useful for users & collections.

Example case:

1) A user inputs the URL to a post on PH on website/app X
2) API call to the (new) lookup endpoint at the PH API
3) Return of product ID (user ID/collection ID)
4) API call to the respective API endpoint with the returned ID
5) Return of the requested data

(Could also pull 3-5 together and just return the requested data straight away.)

Soundcloud does this very well: https://developers.soundcloud.com/docs/api/reference#resolve

P.S.: I'll be able to hack around this if needed but would argue that this could be useful to the community as a whole & thus should be an official endpoint.

**Comment by sleinadsanoj** [comment]
P.S.: I'll be able to hack around this if needed but would argue that this could be useful to the community as a whole & thus should be an official endpoint.

**Comment by lfittl** [comment]
I like the idea - whats your use case for this?

We can certainly look into adding this, however it helps to understand the context so we can prioritize this correctly, since its not something we need for our own apps right now.

**Comment by andreasklinger** [comment]
is your goal to query products by slug? as in `/posts/tinder` => id response

**Comment by sleinadsanoj** [comment]
@andreasklinger: yes, that would work (either slug or full URL, same difference)

@lfittl: Use case would be to embed products from PH into user-generated posts. The simply copy & pastes the link & it would show the product, including the makers & upvote + comment counts.

As I mentioned this is something I could hack together from scraping the html of the site the users link to & finding the product ID in there, saving the ID to my DB & associating it with the URL, but it would be (much) better if it was implemented at the source. :)

**Comment by sleinadsanoj** [comment]
... did not mean to close ;)

**Comment by andreasklinger** [comment]
closing this for now given we didnt work on it for longer time
