### ISSUE TITLE
Max number of users returned by /users endpoint is 50, not 100 as said in docs

### ISSUE THREAD

**Issue by andybons** [producthunt/producthunt-api#56]
From [here](https://api.producthunt.com/v1/docs/users/users_index_get_all_users) and [here](https://api.producthunt.com/v1/docs/users/users_index_get_all_users_%60newer%60_than_the_provided_id)...

per_page	Filter parameter: define the amount of records sent per call **(max 100)**

**Comment by mscoutermarsh** [comment]
Thanks, sorry about that. Our docs are wrong. Will fix.

**Comment by andybons** [comment]
All good. Keep up the good work! :+1:
