### ISSUE TITLE
Creating PH account after API auth results in error

### ISSUE THREAD

**Issue by mattfogel** [producthunt/producthunt-api#57]
Hi, in testing an app I'm working on, I authed with a Twitter account that is not already a PH account. Twitter redirects me to the PH screen asking for my email and job/company, then I get redirected to https://api.producthunt.com/my/welcome which gives a 404 ("Oops. Can't find that page")

This isn't a blocker for our app, but thought you might want to know that it's occurring.

**Comment by lfittl** [comment]
Good catch - thats a bug on our end.

**Comment by mscoutermarsh** [comment]
hey @mattfogel, thanks! Fix for this will be deployed tonight. Closing this now.
