### ISSUE TITLE
When does Collections "updated_at" change?

### ISSUE THREAD

**Issue by jsneedles** [producthunt/producthunt-api#60]
Hi,

Wondering when collections' "updated_at" field is changed?  Does this apply only to the root collection (i.e its color or title changes) or does it apply also when a post is added/removed?

Thanks!

**Comment by andreasklinger** [comment]
Also when a post gets added

**Comment by andreasklinger** [comment]
Closing for now - feel free to proof me wrong - stuff constantly changes
