### ISSUE TITLE
Better docs

### ISSUE THREAD

**Issue by raulriera** [producthunt/producthunt-api#61]
Would be nice if the example responses in the docs could be easily copy pasted. A syntax highlighter would take care of this

**Comment by andreasklinger** [comment]
I am unsure if i fully understand this

this is copypasted
```
{
  "users" : [
    {
      "id" : 11,
      "name" : "Karl User the 345th",
      "headline" : "Product Hunter",
      "created_at" : "2015-05-07T06:13:51.228-07:00",
      "username" : "producthunter345",
      "website_url" : "http://awesome.io",
      "image_url" : {
        "30px" : "http://avatars-cdn.producthunt.com/11/30?1431004431",
        "32px" : "http://avatars-cdn.producthunt.com/11/32?1431004431",
        "40px" : "http://avatars-cdn.producthunt.com/11/40?1431004431",
        "44px" : "http://avatars-cdn.producthunt.com/11/44?1431004431",
        "48px" : "http://avatars-cdn.producthunt.com/11/48?1431004431",
        "50px" : "http://avatars-cdn.producthunt.com/11/50?1431004431",
        "60px" : "http://avatars-cdn.producthunt.com/11/60?1431004431",
        "64px" : "http://avatars-cdn.producthunt.com/11/64?1431004431",
        "73px" : "http://avatars-cdn.producthunt.com/11/73?1431004431",
        "80px" : "http://avatars-cdn.producthunt.com/11/80?1431004431",
```

**Comment by raulriera** [comment]
Yes, but how do you "easily" copy and paste all the response in that example? it's not very pleasant... something like a syntax highlighter or a button that puts it in the clipboard would be nice. Moe like a "nice to have" than a bug obviously

**Comment by andreasklinger** [comment]
maybe it's a browser problem

Am i understanding it correctly that for you cmd+c and cmd+v doesnt keep the formating ?

**Comment by raulriera** [comment]
Sorry, I meant to say "selecting the whole response" it's not pleasant.

**Comment by andreasklinger** [comment]
It's developer docs not a wellness spa ;)

But i get your point.

With the next major iteration we will see what we can do - maybe adding better highlighters that provide those features would help - do you have a recommendation for a script?

**Comment by raulriera** [comment]
A good experience in everything is key :dancers: , but now that I dig more into it... it's more of a "OS X" issue, the browsers (Safari and Chrome) don't follow the cursor when selecting "down", if I go to the bottom of the response and select from the bottom up, then the page scrolls with my cursor.
