### ISSUE TITLE
how to get posts between two date or specific date range?

### ISSUE THREAD

**Issue by shubhamkhanna** [producthunt/producthunt-api#62]
i need posts between two specific date range like "v1/posts/day=2015-05-16and2015-05-18"

if anyone knows please let me know ASAP.

Thanks!

**Comment by andreasklinger** [comment]
You can't do ranges atm 
you can do the days and then use newer=last_id to continue fetching as stream
or simply fetch all days in the range

**Comment by andreasklinger** [comment]
will archive this - feel free to reopen
