### ISSUE TITLE
Simple Rails examples?

### ISSUE THREAD

**Issue by cqcn1991** [producthunt/producthunt-api#63]
I'm not quite familiar with working with API. I want to fetch the daily post of `product hunt`. And this is what I end up with

    task :fetch_product_hunt => :environment  do
      query = "http://api.producthunt.com/v1/posts"
      access_token = `My Developer Token`
      response = HTTParty.get(query,
                              :headers => {'Accept' => 'application/json',
                                           'Content-Type' => 'application/json',
                                           'Authorization' => access_token,
                                           'Host' => 'api.producthunt.com'}).body
      decode_response =  ActiveSupport::JSON.decode(response)
      puts decode_response
    end

And I'm getting `{"status"=>"404", "error"=>"Not Found"}`.

Is there any example that I can learn from? And Do I need to `POST /v1/oauth/token` first?

**Comment by cqcn1991** [comment]
Now I've solved this, I change `query = https://`, and `access_token = 'Bearer Bearer 0c1d3...`

**Comment by mscoutermarsh** [comment]
Great! :grinning: 

Btw, this may be useful to you. Or at least show some examples to get you started.

https://github.com/mikejarema/hunting_season cc @mikejarema
