### ISSUE TITLE
Image rendering issue?

### ISSUE THREAD

**Issue by cqcn1991** [producthunt/producthunt-api#64]
I've build a small demo using PH API. (http://productchaseapp.herokuapp.com/), and the images make pages looks much easier. 
The problem is that, image from `url2img` does not render on mobile devices. When I using iPhone or tablet, the images are all blank. Is it a decision made by PH, or a problem?

**Comment by andreasklinger** [comment]
This sounds unrelated to us or `url2png` - we just export that url and and i dont think that they care for how it's used (it's just a GET request to an img file not a js request)

would be surprised if they do clever optimization here

are you sure the error is not on your side somehow?

**Comment by cqcn1991** [comment]
When I use different `user-agent` (using Chrome's mobile device emulator), the images stop rendering.
And I think that's their approach when mobile device try to access big size images.

**Comment by cqcn1991** [comment]
I think they disabled the rendering when using as `backgroun-image` (that's a small hack I'm using when dealing with special image sizes). And now I'm going to change my `html`, problem solved.

**Comment by andreasklinger** [comment]
ok 
happy to hear

ping us if we can help
