### ISSUE TITLE
A possibility to limit what's returned on GET /v1/posts

### ISSUE THREAD

**Issue by marmelroy** [producthunt/producthunt-api#65]
I'm using GET /v1/posts to retrieve today's top hunt. 

The request is currently very slow (averaging ~1.5s) because it's returning a lot of data (including some complex user joins I don't need). 

It'll be great if it were possible to limit the amount of data returned for better speed (e.g. a count, limit or exclude param). Can't find anything to that effect in the docs.

**Comment by lfittl** [comment]
Thanks for the input - that definitely would be a useful addition.

We'll review this in the team and implement when there is time - can't give any specific ETA yet though. But as I understand its primarily slow for you right now, not stopping you from using the API :)

**Comment by andreasklinger** [comment]
Not plan to do w/in V1 - should be possible in v2 of the api

closing this for now

**Comment by marmelroy** [comment]
Great. Thanks @andreasklinger.
