### ISSUE TITLE
Ordering on /collections endpoint not working as expected

### ISSUE THREAD

**Issue by mikejarema** [producthunt/producthunt-api#67]
I'm trying to do an `asc` sort on `created_at` on `/collections`.

The following two calls isolate what appears to be a bug.

The following correctly yields the most recently added collection:
`curl -H "Authorization: Bearer MYTOKEN" "https://api.producthunt.com/v1/collections?sort_by=created_at&order=desc&per_page=1"`

I would expect the following to return the first collection ever created, but instead it returns the same as above, the most recently created:
`curl -H "Authorization: Bearer MYTOKEN" "https://api.producthunt.com/v1/collections?sort_by=created_at&order=asc&per_page=1"`

With a bit more poking around, it seems to me like the `sort_by` and `order` parameters are ignored for any query to this endpoint.

Bug?

**Comment by andreasklinger** [comment]
from what i understand this is most likely a bug
unfort we didnt have the time so far to fix this and most likely wont in near future 
sorry for this

closing this for now - feel free to reopen with follow up questions
