### ISSUE TITLE
What url does "Find posts with given url" require? 

### ISSUE THREAD

**Issue by gandhisahil** [producthunt/producthunt-api#69]
With respect to the doc page https://api.producthunt.com/v1/docs/posts/posts_all_find_posts_with_given_url_(eg_to_avoid_duplicates)
Does it take? :
1.) the ph redirect url of a product, (eg: https://www.producthunt.com/r/fb4d8a60dbe460/36541)
2.) a ph url for the product, or (eg: https://www.producthunt.com/tech/myeffecto)
3.) the direct url of the product (eg: http://www.myeffecto.com/)

And in all these scenarios, will there be more than one product in the response?

**Comment by andreasklinger** [comment]
The direct url of the product

**Comment by andreasklinger** [comment]
And there are as many products as are known with the url
