### ISSUE TITLE
Paginating the result of live#index

### ISSUE THREAD

**Issue by sungwoncho** [producthunt/producthunt-api#71]
Currently `/v1/live` returns 50 results at maximum. If there are more than 50 live entries in the query, there should be a way to paginate the result (much like what GitHub API does).

I could not find pagination in the doc. Is there an undocumented way to access paginated results?

**Comment by lfittl** [comment]
@sungwoncho First of all, sorry for the late reply!

I think you should be able to use `newer=ID` and `older=ID` to paginate through the events, much like on the comments endpoint (https://api.producthunt.com/v1/docs/comments_and_comment_threads/comments_index_fetch_a_stream_of_all_recent_comments)

Let me know if that doesn't work, then we can take a look :)

**Comment by mscoutermarsh** [comment]
@sungwoncho this is getting fixed. Will be live in a few hours. Sorry about that. :star2:
