### ISSUE TITLE
"The redirect uri included is not valid."

### ISSUE THREAD

**Issue by imns** [producthunt/producthunt-api#72]
I'm trying to authenticate a user via the API and I keep getting this error: `The redirect uri included is not valid.`.  

I've created an application as per the docs.  I'm using the documentation here https://api.producthunt.com/v1/docs/oauth_user_authentication/oauth_authorize_ask_for_access_grant_code_on_behalf_of_the_user as a guide.

The URL I'm hitting looks like this `https://api.producthunt.com/v1/oauth/authorize?client_id={my code here}&redirect_uri=http%3A%2F%2Fmysite.com%2Fcallback%2F&response_type=code&scope=public`

I've set the redirect URI in the API Dashboard to be the same as what I'm passing above.  

I'm not sure what I'm doing wrong, but no matter what I set my `redirect_uri` to, I always get that error message.

**Comment by andreasklinger** [comment]
hi nate

sorry for those troubles - i will see if i can take a look into it tonight or tomorrow

**Comment by imns** [comment]
Thanks @andreasklinger.  

If it helps, I'm trying to do it with https://github.com/atom/electron and JavaScript, but it seems like that shouldn't matter since I'm just hitting a URL.

**Comment by lfittl** [comment]
@imns Is the `redirect_uri` you're passing a publicly accessible URL, or e.g. localhost?

**Comment by imns** [comment]
@andreasklinger yes, but I have tried both ways.  I've also tried `http` and `https` to see if it makes a difference but it doesn't.

**Comment by lfittl** [comment]
@imns Ok, thats odd - I'll defer to Andreas on this one.

In general, assuming its a public URL and you've set it to be the same in both the API dashboard and in the request, it should work (tm).

**Comment by imns** [comment]
Just out of curiosity what are the rules for the redirect url?  Do you have to pass the same URL you have set in the API dashboard?  Can it be `http://localhost` or does it have to be publicly accessible? Does it have to be `https`?

**Comment by jschuur** [comment]
@imns From my own testing right now, I had your error just now too for http://localhost:3000, and it went away once I made sure the API dashboard URI was the same as the redirect URI parameter.

**Comment by vesln** [comment]
@jschuur awesome! closing this for now, feel free to reopen if necessary
