### ISSUE TITLE
My friend...pagination is not working

### ISSUE THREAD

**Issue by AndreiD** [producthunt/producthunt-api#76]
Pagination is broken...

why don't you put a NORMAL pagination with start_page=x,end_page=y,limit=z

I don't understand that ID? is the id of the post ? but if i try to get posts in one category they have different ids. from where I know which one is the "oldest" ?

**Comment by AndreiD** [comment]
what I try to achieve.

get the latest posts in category games
and when I scroll down, to load more.

can you give me an example how to do it because your api documentation on this sucks or I'm to stupid to understand it.

**Comment by RStankov** [comment]
Hi,

Calling `/v1/posts/all?search[category]=games` will return something like: 

```
{
  "posts": [{
    "id": 10000,
    // other attributes
  }, {
    "id": 9999,
    // other attributes
  }, {
    "id": 9998,
    // other attributes
  }]
}
```

The last post id in this case is `9998`. 

You can than use it to fetch the next batch by calling - `/v1/posts/all?search[category]=games&older=9998`. 

More information: 

https://api.producthunt.com/v1/docs/posts/posts_all_get_all_the_newest_posts

**Comment by AndreiD** [comment]
one second..not so fast.

I want it from here

https://api.producthunt.com/v1/categories/games/posts

and I have id's like:   "id": 44658, "id": 44690, "id": 44683,.... not ordered.

**Comment by RStankov** [comment]
`https://api.producthunt.com/v1/categories/games/posts` is giving you posts by days - [docs](https://api.producthunt.com/v1/docs/posts/posts_index_request_previous_day_with_%60days_ago%60_parameter_(for_given_category))

The endpoint is returning posts grouped by days and sorted as they are in the site.

You can get posts for several days by:
```
https://api.producthunt.com/v1/categories/games/posts?days_ago=0
https://api.producthunt.com/v1/categories/games/posts?days_ago=1
https://api.producthunt.com/v1/categories/games/posts?days_ago=2
https://api.producthunt.com/v1/categories/games/posts?days_ago=3
```

**Comment by AndreiD** [comment]
all right. Thanks, this is what I was looking for

**Comment by andreasklinger** [comment]
btw we dont do `page=1,2,3,4` pagination because it's hard to optimize for the database
https://use-the-index-luke.com/sql/partial-results/fetch-next-page

closing this issue for now

**Comment by AndreiD** [comment]
moky Andreas. you can close it for later too.

**Comment by danielhorizon** [comment]
Did this ever get fixed with v2?
