### ISSUE TITLE
collections#index - Filter by Category endpoint not working.

### ISSUE THREAD

**Issue by shivkanthb** [producthunt/producthunt-api#77]
the filter by category (for any category) returns the following
{
error: "not_found",
error_description: "We could not find any object with this ID"
}
The other endpoints (new collections, featured collections) are working as expected. Its just this category filter endpoint.

**Comment by vesln** [comment]
Could you please include the HTTP request as well?

**Comment by RStankov** [comment]
Can you provide me with the URL which returns this error?

Categories should be specified by their slug: `tech`, `games`, `books`, `podcasts`. Like:

```
/v1/categories/games/posts
/v1/posts/all?search[category]=games
```

**Comment by shivkanthb** [comment]
Im really sorry I forgot to mention the complete endpoint. 
Its for the collections.
The docs mention.
GET /v1/collections?search[category]=category-1 

But I got it working. 'category-1' has to be replaced by their slug. Would be nice if this was mentioned in the docs.
Thank you.

**Comment by RStankov** [comment]
I would try to improve the wording there when we update the API docs next time.
