### ISSUE TITLE
Too Much Data in the users#show endpoint

### ISSUE THREAD

**Issue by karlcoelho** [producthunt/producthunt-api#78]
Almost 1.4MB of JSON! It makes my app really show. Maybe you can reference the user and post id's instead of giving the whole dataset

**Comment by RStankov** [comment]
Hi,

You can reduce the data for `users#show`, by passing: `exclude[]=relationships` as shown here:

https://api.producthunt.com/v1/docs/users/users_show_exclude_%60relationships%60
