### ISSUE TITLE
Schedule post via the API

### ISSUE THREAD

**Issue by Vkt0r** [producthunt/producthunt-api#79]
Recently I have the necessity to post a new product, but rarely the time to post it was -6 hour of differences from my country and I come with the idea to develop an app schedule the post of products using the  ProductHunt API, but I don't see any doc about it and I read that is read-only. 

There is any possibility to make a post of a new product with the tags as in the web are : Name, Link, App Link, Description, etc  via the API?

**Comment by lfittl** [comment]
Unfortunately at this point the API is read-only, we don't give out write permissions at this point.

Love your project idea, sorry we can't support it at the moment!

**Comment by Vkt0r** [comment]
Uhmm too bad, I hope this can be a feature soon in Product Hunt, it would be great!!!, thanks for the help!!!
