### ISSUE TITLE
How to get the Video URL attached to the original post?

### ISSUE THREAD

**Issue by rajasimon** [producthunt/producthunt-api#80]
I explored the Api other day and I found that there is no video link given in the response say example if Youtube video attached to the Product Hunt posts then I expected to see the youtube link in Api response. Is that something I'm missing or any feature plan ? or it will not come ?

**Comment by RStankov** [comment]
Hi, we have 3 types of media: 

__image__:

```json
{
  "media_type" : "image",
  "image_url" : "http://placehold.it/850x850.png",
  "metadata" : {}
}
```

__video__:

```json
 {
  "media_type" : "video",
  "image_url" : "http://placehold.it/850x850.png",
  "metadata" : {
    "platform": "youtube",
    "video_id": "youtube video id"
  }
}
```

__audio__:

```json
{
  "media_type" : "audio",
  "image_url" : "http://placehold.it/850x850.png",
  "metadata" : {
    "url": "http://example.com/podcast.mp3"
  }
}
```

In `image_url` is the image representation of the media - thumbnail in case of video and coverart in case of audio.
In `metadata` we store the additional information you need for this media. In  your case `platform` and `video_id`.

Media can be attached as `thumbnail` or `media` to `posts`. Here is an API example of all media types:

https://api.producthunt.com/v1/docs/posts/posts_show_response_contains_all_media
