### ISSUE TITLE
Problem with paging users#index 

### ISSUE THREAD

**Issue by emorling** [producthunt/producthunt-api#81]
The followers#index returns two id's for each user, and only one of them works for paging. 

In the result 
{followers : [ [id: XXX, user:[id: YYY, ....] ]}
the XXX works, but not YYY.

However when retrieving users#index only one ID is returned. 

And it seems that this ID is the wrong one for paging?

**Comment by lfittl** [comment]
In the `followers#index` case the `XXX` id is the internal id of the association (and therefore the one you need to use for pagination)

For `users#index` it should work to use the last `id` in the set and pass that as `?newer=ID` to the next call. Let us know if thats not working.

**Comment by emorling** [comment]
Thanks for a swift reply.

It appears to not be working. My guess it's the wrong ID being passed in the users#index, because I am seeing the same results being returned and this problem was happening before I realized which ID I should be using for followers#index.

**Comment by lfittl** [comment]
Hmm. Could you maybe share the exact requests you are running? (with the API keys removed)

From reading our code this should be working fine (and the same way for both endpoints), happy to investigate further.

**Comment by emorling** [comment]
The first time header

```
GET /v1/users?per_page=1 HTTP/1.1\r\nAccept: application/json\r\nContent-Type: application/json\r\nAuthorization: Bearer KEY r\nHost: api.producthunt.com\r\nConnection: close\r\n\r\n
```

The second time header

```
GET /v1/users?per_page=1&params%5Bolder%5D=429085&params%5Bper_page%5D=1 HTTP/1.1\r\nAccept: application/json\r\nContent-Type: application/json\r\nAuthorization: Bearer KEY\r\nHost: api.producthunt.com\r\nConnection: close\r\n\r\n
```

**Comment by lfittl** [comment]
You need to use `older` as a simple parameter, not `params[older]`.

See also https://api.producthunt.com/v1/docs/users/users_index_get_all_users_%60newer%60_than_the_provided_id

Let me know if that fixes it :)

**Comment by emorling** [comment]
My god I am an idiot :)

**Comment by lfittl** [comment]
Haha, no worries - happy that we could resolve it :)

And let us know what you build - always curious to see how people use the API 😸
