### ISSUE TITLE
Not getting more then 50 records

### ISSUE THREAD

**Issue by ghost** [producthunt/producthunt-api#82]
Its my first time i am implementing this API and when ever i send a request to get Users, it always return me 50 records as it is mentioned in the documentation per_page max records will be 50.

Is there any way i can get more then 50 records? and what is the best way to get all the users? Will you recommend any library that have already implemented get/set methods?

**Comment by lfittl** [comment]
Hi @osama1988 - could you check if this is the same problem as https://github.com/producthunt/producthunt-api/issues/81

If not, please post the exact requests you are sending, with the API key removed.

Thanks! 😺

**Comment by osama1988** [comment]
I am using the following library for getting list of users. Please refer function getUsers(). I am not sure about how pagination in this implementation would work(if that is causing the issue).

**Comment by lfittl** [comment]
@osama1988 Which library are you referring to?

**Comment by osama1988** [comment]
Sorry for not mentioning the link. Here it is (https://github.com/jamstarter/ProductHunt-PHP-library)

**Comment by andreasklinger** [comment]
from what i understand unrelated to the actual api - please ask in the library github issues
