### ISSUE TITLE
PH not giving proper user upvotes

### ISSUE THREAD

**Issue by haseebawan** [producthunt/producthunt-api#86]
When we call API for user votes, it gives us an array having a key [''votes] but that count is different from user`s upvote count. We want to know what is the count that your API gives and how can we get upvote count?

**Comment by haseebawan** [comment]
Thought I will bump it up ?

**Comment by andreasklinger** [comment]
upvote counts and votes exported might differ slightly b/c of race conditions/delays and other problems in with the counter cache

how big is the difference?

closing this for now - if you still work on this feel free to reopen with follow up answers/questions
