### ISSUE TITLE
Can't find docs on /authorize endpoint

### ISSUE THREAD

**Issue by daynesh** [producthunt/producthunt-api#91]
There's a reference in the API Docs to: 
> Follow the steps in OAuth User Authentication oauth#authorize to receive an access_grant

However, there doesn't seem to be a link/page on how one should use the /authorize endpoint (query parameters used, scopes supported, etc.).

Only knew the URL based on another issue: https://github.com/producthunt/producthunt-api/issues/88

**Comment by RStankov** [comment]
Hi,

Here is the URL:

https://api.producthunt.com/v1/docs/oauth_user_authentication/oauth_token_use_the_access_grant_code_you_received_through_the_redirect_to_request_an_access_token

**Comment by daynesh** [comment]
@RStankov - This seems to be the page for oauth#token.  But the docs reference oauth#authorize.

**Comment by RStankov** [comment]
@daynesh Actually for some reason our doc tool didn't generate the documentation page for `#authorize`. I'll check why and comeback to you.

**Comment by RStankov** [comment]
Here are the docs:

https://api.producthunt.com/v1/docs/oauth_user_authentication/oauth_authorize_ask_for_access_grant_code_on_behalf_of_the_user

For some reason, during the last deploy they weren't generated.

**Comment by daynesh** [comment]
Thanks!

**Comment by asimona** [comment]
@RStankov it's redirecting to https://api.producthunt.com/v1/docs, and again I can't find the authorize page

**Comment by rohillion** [comment]
Same happened to me, is redirecting to the docs page.
