### ISSUE TITLE
Best way to pull a list of makers on ProductHunt

### ISSUE THREAD

**Issue by SaijoGeorge** [producthunt/producthunt-api#95]
I was wondering if there is a way for me to pull a list of makers on ProductHunt. I want to get a list of makers , their vote count, product count and twitter id.  Do you folks grab the country data for them if so that would be awesome. 

I am guessing at the moment I have to pull all users using these

users#index - Get all users 

then filter out the makers from that. 

Also, with the rate limit of 900 / 15 mins can we get that relaxed? 

CC: ing the dev as well @gssumesh

**Comment by andreasklinger** [comment]
From my current understanding we do not provide a matching endpoint for this usecase
sorry

closing for now - feel free to reopen with related/followup questions

**Comment by SaijoGeorge** [comment]
Hi Andreas

Would it be possible to get a CSV dump with a list of users, their vote count, product count and twitter id?

I believe once we have the initial data we can use [users#index - Get all users `newer` than the provided id](https://api.producthunt.com/v1/docs/users/users_index_get_all_users_%60newer%60_than_the_provided_id) to get the new users. #prettyplease 

Happy to email you more info on what we are building with this. 

CC: @gssumesh
