### ISSUE TITLE
Followup : Best way to pull a list of makers on ProductHunt

### ISSUE THREAD

**Issue by SaijoGeorge** [producthunt/producthunt-api#96]
Hi Andreas

Reg : https://github.com/producthunt/producthunt-api/issues/95

Would it be possible to get a CSV dump with a list of users, their vote count, product count and twitter id?

I believe once we have the initial data we can use users#index - Get all users newer than the provided id to get the new users. #prettyplease

Happy to email you more info on what we are building with this.

CC: @gssumesh

**Comment by andreasklinger** [comment]
we currently dont do CSV exports anymore

unfortunately our db models change quite frequently and it's a p.i.t.a. to keep the csv export scripts working

if you need it for super-important reasons (eg your academic master thesis) please me know and i will see if i can make it work in my off hours
