### ISSUE TITLE
Pull comments and votes for product 'name'

### ISSUE THREAD

**Issue by PaulieScanlon** [producthunt/producthunt-api#97]
Hi, whats the best way to make a call to actual product. So if i wanted to get all comments and votes for https://www.producthunt.com/tech/ubeen

The below doesn't work, but that's probably because i'm doing it wrong:

https://api.producthunt.com/v1/posts/all?search[url]=Ubeen'

any ideas?

Cheers!

**Comment by devladinci** [comment]
Hey @PaulieScanlon 

To get product comments you can either:
1) [Get details for given post](https://api.producthunt.com/v1/docs/posts/posts_show_get_details_of_a_post)
2) [Fetch stream of comments](https://api.producthunt.com/v1/docs/comments_and_comment_threads/comments_index_fetch_a_stream_of_all_recent_comments) where `search[post_id] = POST_ID`

What about votes - [PostVotes](https://api.producthunt.com/v1/docs/postvotes/votes_index_see_all_votes_for_a_post)

Vlad

**Comment by PaulieScanlon** [comment]
Hey Vlad thanks for that!

ok so looking up all comments on a post works now:
https://api.producthunt.com/v1/comments?search[Ubeen]

The votes thing though, can that work in the same way?

This is wrong:
https://api.producthunt.com/v1/posts/1/votes?search[Ubeen]
as is this
'https://api.producthunt.com/v1/posts/Ubeen/votes'

What am i missing here?

Cheers!

**Comment by devladinci** [comment]
@PaulieScanlon `https://api.producthunt.com/v1/posts/1/votes?search[Ubeen]` should become -> `https://api.producthunt.com/v1/posts/__UBEEN_POST_ID__/votes` `productId` is a must for this query :)

Cheers

**Comment by PaulieScanlon** [comment]
hey, thanks man! so, final question, how would a user know the post id in order to look it up in my app?

**Comment by devladinci** [comment]
Hm i think you will need 2 queries. 

1. `GET` product by given name. where you can get the `id`
2. `GET` all votes for product with `id`

Note: It is assumed, that you should have post id in order to get the details about it. Thats why `v1/posts/POSTID/votes` and related work with `id`

Hope this will help. 👍

**Comment by PaulieScanlon** [comment]
Ok cool, i'll investigate that route! thanks for your help man! very speedy and much appreciated!

**Comment by PaulieScanlon** [comment]
ah, ok don't worry i was missing an '&'
https://api.producthunt.com/v1/posts/'+statData.postId+'/votes?newer='+statData.lastVoteId+'&order=asc

You can close this issue now. This one's my bad! :)
