### ISSUE TITLE
max votes

### ISSUE THREAD

**Issue by PaulieScanlon** [producthunt/producthunt-api#99]
Hi, just wondering if you're able to tell me if the votes has any kind of limit on it? 50 per page is fine, i'm using:

/votes?per_page=50&newer='+statData.lastVoteId+'&order=asc

on a loop where statData.lastVoteId is the last vote idea before the loop starts again.

However, I've been running some tests and my async.easeSeries loop correctly shows the same votes total as as "votes_count" that's returned in the posts object, except when the vote count exceeds 250. 

It seems that either my loop can only handle up to 250 votes ... which is weird, or that the api doesn't return all votes.

This a good URL to investigate canva.com on as it has 584 votes
https://www.producthunt.com/tech/canva

Are you able to investigate?

Thanks in advance.

**Comment by andreasklinger** [comment]
i am cleaning up the issues - this hasn't been responded to yet - sorry for that
if this is still an active issue please let me know and i will take a look!

**Comment by PaulieScanlon** [comment]
This is fine to close. It was an issue with my code not the api.

Thanks!
